### ISSUE TITLE
Block models have no lighting

### ISSUE THREAD

**Issue by mezz** [way2muchnoise/JustEnoughResources#1]
![2016-01-10_09 53 09](https://cloud.githubusercontent.com/assets/916092/12222978/15f74d40-b780-11e5-9b88-b99a764433f7.png)

Compare the farmland to the 3d blocks in the item list, there is no lighting.

**Comment by way2muchnoise** [comment]
fixed in 64f95763ae1c00b060b68f133c8cededa8a77f26
