### ISSUE TITLE
JER 0.5.4.68 loads but doesnt seem to do anything

### ISSUE THREAD

**Issue by gmoff01** [way2muchnoise/JustEnoughResources#101]
Using JER 0.5.4.68 and JEI 3.13.2.363 (specifically the FTB Direwolf20 1.10 pack) I can tell that JER is loading (I can get to its settings via the menu) but it doesnt seem to be doing anything.  No mob drop or loot chest listings, and the /profile command comes back with an invalid command error.

**Comment by way2muchnoise** [comment]
Yeah, the version included in the dw20 is broken. Update it manually. The pack update should be this week normally tho.
