### ISSUE TITLE
stuck in version JustEnoughResources-1.10.2-0.5.6.84

### ISSUE THREAD

**Issue by bloodyraoul** [way2muchnoise/JustEnoughResources#103]
if I try to update to newer version, I cannot connect anymore to my server.
I stay a long time to the "loggin...." screen, then I receive a disconnect from the server.
I dont really have logs to show you
Do you know what's happen ? already know this issue ?

Thanks

**Comment by way2muchnoise** [comment]
At least try the [latest release (0.5.7.87)](https://minecraft.curseforge.com/projects/just-enough-resources-jer/files/2345082) first.

**Comment by bloodyraoul** [comment]
The JustEnoughResources-1.10.2-0.5.7.87 doesnt work, same issue
I use jei_1.10.2-3.13.6.387

**Comment by way2muchnoise** [comment]
is this a mod pack? Is there anything in the logs what so ever?

**Comment by way2muchnoise** [comment]
Closing due to no response
