### ISSUE TITLE
[Feautre Request?] world-gen.json

### ISSUE THREAD

**Issue by ZorbaHerbalist** [way2muchnoise/JustEnoughResources#109]
I'm using /profile to generate ores distribution in Overworld, then going to Nether and again use /profile to generate for Nether. world-gen.json is overwritten and after restart Minecraft shows only ore distribution for Nether.

Is there any possibility to append ore distribution for multiple dimensions?

**Comment by way2muchnoise** [comment]
Use /profile (chunks) all, that will do all dimensions
