### ISSUE TITLE
World crashing after using the /profile 10 all command

### ISSUE THREAD

**Issue by SenpaiWithDiabetes** [way2muchnoise/JustEnoughResources#113]
**Hey I followed your advice 
"You can even use /profile [chunk amount] [all] to create a world-gen-scan.json that will get the distributions"
And typed in /profile 10 all in my modded survival world..it started "profiling" all the dimensions and as soon as it finished the mining world,it started profiling the Aether and froze up instantly...
Now as soon as I try to enter the world it crashes... 
I do not have any recent backups on the world and it is pretty much the only one I play constantly on..
Could you please look at the crash report as I am completely inexperienced in reading them..
It launches minecraft normally and other worlds work perfectly normal.

Here is the crash report (might be a bit long sorry!)**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  CoFH Loading Plugin (CoFH-Core-1.10.2.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  ChiselCorePlugin (Chisel-Mod-1.10.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.13r.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 4/25/17 5:01 PM
Description: Exception while updating neighbours

java.lang.ClassCastException: crazypants.enderio.machine.vacuum.TileXPVacuum cannot be cast to WayofTime.bloodmagic.tile.TileDemonCrystal
	at WayofTime.bloodmagic.block.BlockDemonCrystal.func_189540_a(BlockDemonCrystal.java:65)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at crazypants.enderio.conduit.AbstractConduitNetwork.sendBlockUpdatesForEntireNetwork(AbstractConduitNetwork.java:139)
	at crazypants.enderio.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:448)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:393)
	at crazypants.enderio.conduit.liquid.AbstractTankConduit.updateEntity(AbstractTankConduit.java:199)
	at crazypants.enderio.conduit.liquid.LiquidConduit.updateEntity(LiquidConduit.java:91)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:241)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at WayofTime.bloodmagic.block.BlockDemonCrystal.func_189540_a(BlockDemonCrystal.java:65)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)

-- Block being updated --
Details:
	Source block type: ID #974 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block: bloodmagic:BlockDemonCrystal[age=0,attached=up,type=default]
	Block location: World: (446,65,-656), Chunk: (at 14,4,0 in 27,-41; contains blocks 432,0,-656 to 447,255,-641), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at crazypants.enderio.conduit.AbstractConduitNetwork.sendBlockUpdatesForEntireNetwork(AbstractConduitNetwork.java:139)
	at crazypants.enderio.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:448)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:393)
	at crazypants.enderio.conduit.liquid.AbstractTankConduit.updateEntity(AbstractTankConduit.java:199)
	at crazypants.enderio.conduit.liquid.LiquidConduit.updateEntity(LiquidConduit.java:91)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:241)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40)

-- Block entity being ticked --
Details:
	Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
	Block type: ID #974 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (446,71,-656), Chunk: (at 14,4,0 in 27,-41; contains blocks 432,0,-656 to 447,255,-641), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Actual block type: ID #858 (tile.mod.chiselsandbits.chiseled_ice // mod.chiselsandbits.chiseledblock.BlockChiseled)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 630 Drop: 0
	Level seed: 43125346543
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (488,130,-834), Chunk: (at 8,8,14 in 30,-53; contains blocks 480,0,-848 to 495,255,-833), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 16288997 game time, 9676684 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 93415 (now: false), thunder time: 58060 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1556049352 bytes (1483 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D6 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	cofhcore{4.0.2} [CoFH Core] (CoFH-Core-1.10.2.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r104} [Actually Additions] (ActuallyAdditions-1.10.2-r104.jar) 
	UCHIJAAAA	aether{1.10.2-r1} [Aether II] (Aether-2-1.10.2-Indev.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJAAAA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2(1).jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar) 
	UCHIJAAAA	arsmagica2{1.5.017} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft-Mod-1.10.2.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	immersiveengineering{0.10-50} [Immersive Engineering] (ImmersiveEngineering-0.10-50.jar) 
	UCHIJAAAA	JEI{3.14.6.411} [Just Enough Items] (jei_1.10.2-3.14.6.411.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.2-71} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.2-71.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	chancecubes{1.10.2-2.3.4.164} [Chance Cubes] (Chance-Cubes-Mod-1.10.2.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-Mod-1.10.2.jar) 
	UCHIJAAAA	chiselsandbits{12.11} [Chisels & Bits] (Chisels-and-Bits-Mod-1.10.2.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal(1).jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.13} [CoroUtil Library] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (Custom-NPCs-Mod-1.10.2.jar) 
	UCHIJAAAA	customizeddungeonloot{1.0.0} [§eCustomized Dungeon Loot] (Customized-Dungeon-Loot-Mod-1.10.2.jar) 
	UCHIJAAAA	darkutils{1.1.7.111} [Dark Utilities] (DarkUtilities-1.10.2-1.1.7.111.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	DungeonTactics{DT0.9.4} [DungeonTactics] (Dungeon-Tactics-Mod-1.10.2.jar) 
	UCHIJAAAA	eplus{4.1.0.102} [Enchanting Plus] (Enchanting-Plus-Mod-1.10.2.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.103} [EnderStorage] (EnderStorage-1.10.2-2.2.1.103-universal.jar) 
	UCHIJAAAA	tesla{1.2.1.50} [TESLA] (Tesla-1.10.2-1.2.1.50.jar) 
	UCHIJAAAA	energyconverters{1.0} [Energy Converters] (energyconverters_1.10.2-0.3.0.5.jar) 
	UCHIJAAAA	ExtraBitManipulation{1.10.2-2.3.1} [Extra Bit Manipulation] (Extra-Bit-Manipulation-Mod-1.10.2.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.2.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.1.0.4} [Zero CORE] (zerocore-1.10.2-0.1.0.4.jar) 
	UCHIJAAAA	bigreactors{1.10.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.27.jar) 
	UCHIJAAAA	sonarcore{3.2.6} [SonarCore] (SonarCore-1.10.2-3.2.6.jar) 
	UCHIJAAAA	fluxnetworks{1.1.9} [FluxNetworks] (FluxNetworks-1.10.2-1.1.9.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.6} [Giacomo's Foundry] (GiacomosFoundry1.10.2-1.3.6.jar) 
	UCHIJAAAA	gravestone{1.5.10} [Gravestone] (GraveStone Mod 1.5.10.jar) 
	UCHIJAAAA	grimoireofgaia{1.5.1} [Grimoire of Gaia 3] (Grimoire-of-Gaia-3-Mod-1.10.2.jar) 
	UCHIJAAAA	hammercore{1.2.3} [Hammer Core] (HammerCore_1.10.2-1.2.3.jar) 
	UCHIJAAAA	ichunutil{6.2.0} [iChunUtil] (iChunUtil-1.10.2-6.2.0.jar) 
	UCHIJAAAA	imaginary{1.0.2} [Imaginary] (Imaginary-Mod-1.10.2.jar) 
	UCHIJAAAA	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (Level-Up-Mod-1.10.2.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-Mod-1.10.2.jar) 
	UCHIJAAAA	MapWriter{2.6.19} [MapWriter] (Mapwriter-2-Mod-1.10.2.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.6.2115} [MineColonies] (minecolonies-universal-1.10.2-0.6.2115.jar) 
	UCHIJAAAA	craftelytra{1.1} [Craftable Elytra] (modid-1.1-1.10.2.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.10.2.jar) 
	UCHIJAAAA	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.11} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.11.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	rdt{0.0.4} [Random Decorative Things] (Random-Decorative-Things-Mod-1.10.2.jar) 
	UCHIJAAAA	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCHIJAAAA	rftools{5.91} [RFTools] (rftools-1.1x-5.91.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	solarfluxreborn{2.13r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.13r.jar) 
	UCHIJAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAA	thermalfoundation{2.0.2} [Thermal Foundation] (Thermal-Foundation-Mod-1.10.2.jar) 
	UCHIJAAAA	thermalexpansion{5.0.2} [Thermal Expansion] (Thermal-Expansion-Mod-1.10.2.jar) 
	UCHIJAAAA	torched{6.0.0} [Torched] (Torched-Mod-1.10.2.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster_1.10.2-1.2.1.23.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (Tree-Chopper-Mod-1.10.2.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (Villager-Market-Mod-1.10.2.jar) 
	UCHIJAAAA	weather2{1.10.2-2.4.8} [Localized Weather & Storms] (Weather-Storms-Tornadoes-Mod-1.10.2.jar) 
	UCHIJAAAA	wct{0.1.27} [Wireless Crafting Terminal] (WirelessCraftingTerminal-1.10.2-0.1.27.jar) 
	UCHIJAAAA	xpplus{1.0} [XP-Plus] (xpplus-1.02.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CoFH Loading Plugin (CoFH-Core-1.10.2.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
ChiselCorePlugin (Chisel-Mod-1.10.2.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
SFRCore (SolarFluxReborn_1.10.2-2.13r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  am2.asm.Transformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.4.1 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from SolarFluxReborn_1.10.2-2.13r.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/CoFH-Core-1.10.2.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/Tesla.class
                  * Tesla API class 'TeslaCapabilities' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/capability/TeslaCapabilities.class
                  * Tesla API class 'ITeslaConsumer' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/ITeslaConsumer.class
                  * Tesla API class 'ITeslaHolder' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/ITeslaHolder.class
                  * Tesla API class 'ITeslaProducer' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/ITeslaProducer.class
                  * Tesla API class 'BaseTeslaContainer' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/implementation/BaseTeslaContainer.class
                  * Tesla API class 'BaseTeslaContainerProvider' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/implementation/BaseTeslaContainerProvider.class
                  * Tesla API class 'InfiniteTeslaConsumer' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaConsumer.class
                  * Tesla API class 'InfiniteTeslaConsumerProvider' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaConsumerProvider.class
                  * Tesla API class 'InfiniteTeslaProducer' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaProducer.class
                  * Tesla API class 'InfiniteTeslaProducerProvider' is loaded from: jar:file:/C:/Users/darko/AppData/Roaming/.minecraft/mods/Tesla-1.10.2-1.2.1.50.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaProducerProvider.class
	Conduit network class crazypants.enderio.conduit.liquid.LiquidConduitNetwork was interrupted while notifying neighbors of changes
                 World.notifyBlockUpdate() at BlockPos{x=446, y=71, z=-656} took 57037ns
                 ForgeEventFactory.onNeighborNotify() at BlockPos{x=446, y=71, z=-656} took 6905ns
                 World.notifyNeighborsOfStateChange() from BlockPos{x=446, y=71, z=-656} to BlockPos{x=446, y=72, z=-656} (bloodmagic:BlockStairs3[facing=east,half=bottom,shape=straight,type=steadfast]) took 1201ns
                 World.notifyBlockUpdate() at BlockPos{x=446, y=66, z=-656} took 58838ns
                 ForgeEventFactory.onNeighborNotify() at BlockPos{x=446, y=66, z=-656} took 4804ns
                 World.notifyNeighborsOfStateChange() from BlockPos{x=446, y=66, z=-656} to BlockPos{x=446, y=65, z=-656} (bloodmagic:BlockDemonCrystal[age=0,attached=up,type=default]) took 13869556ns

	EnderStorage Invalid Fingerprint Reports: 
	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 381.65
	OpenGlRenderer: GeForce GTX 580/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by numinari** [comment]
I too get a crash here, but the system just becomes unresponsive and a crash log. I have a lot of mods here. Going to try just forge/JER alone see whats up. Mine crashes on finishing profiling overworld like it's just blowing up out of memory... and not if I do much of a ton of chunks. I'll report back after I test further.

**Comment by numinari** [comment]
So far it works by itself and forge trying to narrow it down to whatever may be conflicting by removing world gen specific mods.

**Comment by numinari** [comment]
Oh wow I'm dumb, I see it's a blood magic conflict. Hopefully it gets patched soon. Honestly I think the bug is probably in BM.

**Comment by numinari** [comment]
I have a different crash... I still haven't been able to figure out whats causing it

[21:40:53] [Client thread/INFO]: [CHAT] [Overworld] Started profiling
[21:40:54] [Thread-30/ERROR] [jei]: A mod tried to reload JEI, this is no longer supported. See the javadocs for more information
java.lang.RuntimeException
	at mezz.jei.runtime.JeiHelpers.reload(JeiHelpers.java:52) [JeiHelpers.class:?]
	at jeresources.profiling.Profiler.run(Profiler.java:47) [Profiler.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

Guessing I updated a mod to 1.11.2 and now it's causing a problem because it worked with most of the OPs original mods in 1.10. I'm still trying to dissect this, it's a lot of mods. It works fine without anything but JEI and JEI resources loaded.

**Comment by way2muchnoise** [comment]
Profiling a world is very extreme and shouldn't be preformed on a live world. I don't know if you also read

> These features are quite advanced and only recommend for pack makers or experienced players.

Because this is the exact reason it is there, you should be using it on a world with no backups.
