### ISSUE TITLE
[1.12] Crash During Profiling

### ISSUE THREAD

**Issue by SnowShock35** [way2muchnoise/JustEnoughResources#116]
Hello,

I believe I have found a bug in JustEnoughResources for Minecraft 1.12. Here's further details regarding the issue...

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.0.2321
- Just Enough Resources (JER) 1.12-0.7.0.10

### Issue Details

When running the `/profile 1000 all` command, the mod begins to profile the world generation however, after completing the nether and end generation the game crashed to desktop.

### Issue Media

- Crash Report: https://pastebin.com/V7TwhXgC

**Comment by 016Nojr** [comment]
This happens with me aswell.

However, if you look at the logs you can see that it crashes when it starts to profile Dimension 0 (Overworld)

Logs: https://gist.github.com/016Nojr/2de70ba0d7e3e4d242e9be46c8f0f92b

Crash log is located at line 5880
The crash cause (most likely) is located at line 5867

Mod Versions:

Forge: 14.21.1.2396
JEI: 1.12-4.7.1.71
JER: 1.12-0.8.1.14

**Comment by YourPapy** [comment]
Has there been any updates on this? Still experiencing crashes.

MC Version 1.12

Forge Version 14.21.1.2410

Just Enough Items Version 4.7.1.75
Just Enough Resources Version 0.8.1.14
