### ISSUE TITLE
Ore Distribution should be configurable

### ISSUE THREAD

**Issue by mezz** [way2muchnoise/JustEnoughResources#12]
It should read from a config file so that pack makers can customize it for their pack.
Also once that is in place, a tool could automatically generate lists of distributions for every single block in the world.

**Comment by way2muchnoise** [comment]
The format is getting there and seems quite stable atm.

Now to start thinking about that tool

**Comment by mezz** [comment]
Awesome!

**Comment by way2muchnoise** [comment]
I think we can close this as of 0d99d57a3d28106c7d0d237001a292dbf200b563
