### ISSUE TITLE
License concern

### ISSUE THREAD

**Issue by josephcsible** [way2muchnoise/JustEnoughResources#121]
This bit of the license is kind of concerning:
> ###Reserved Rights I reserve the right to change this license at any time, although chances are I won't, because legalese annoys me.

As this stands now, one interpretation could mean that if someone forks this code, following all of the terms, you could change the license to anything, including something prohibiting forking, and then demand that the previously-legal fork be removed, even if it hadn't incorporated any of your other changes since you changed the license. If this were the case, then nobody can really ever do anything without being at your mercy. Can you tweak this to make it clear that this isn't the right interpretation? Maybe adding a sentence like this:
> If I ever change this license, the old version will continue to apply to all revisions prior to the change; the new version will only apply to revisions after the change.

**Comment by way2muchnoise** [comment]
Sure, I can add that.

**Comment by josephcsible** [comment]
Thanks! (Can you update it on Curse too?)
