### ISSUE TITLE
[1.10.2] Clientside crash with Valkyrian Warfare in Mob Drops tab

### ISSUE THREAD

**Issue by dsmall3303** [way2muchnoise/JustEnoughResources#122]
Hey there,
There seems to be a nasty crash when your mod is installed alongside Valkyrian Warfare. Any time you click the "Mob Drops" tab to see what mobs drop what, the client will crash. This happens with any item in the game that has a "Mob Drops" tab. I've verified that this is the problem interaction by disabling Valkyrian Warfare and then opening the last item I was inspecting (wool) in JEI, and found that I did not crash. When I re-enabled the mod and tried again, the crash happened once more.

[I will also be posting this bug to thebest108](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/108) to see if you guys can figure out a fix. I know Valkyrien Warfare does some special stuff behind the scenes, and I think that having an ability to blacklist certain entities from appearing in JEI might put a bandaid on the problem.

[crash-2017-09-10_18.01.07-client.txt](https://github.com/way2muchnoise/JustEnoughResources/files/1291091/crash-2017-09-10_18.01.07-client.txt)
[crash-2017-09-10_18.27.07-client.txt](https://github.com/way2muchnoise/JustEnoughResources/files/1291090/crash-2017-09-10_18.27.07-client.txt)

**Comment by way2muchnoise** [comment]
This seems like something that needs to be fixed on the side of Valkyrian Warfare, but I can help if they need anything from my side.

**Comment by way2muchnoise** [comment]
Closed due to outdated (not gonna fix things for 1.10.2 anymore)
