### ISSUE TITLE
[1.12.2] NPE w/ Other mods when profiling

### ISSUE THREAD

**Issue by SnowShock35** [way2muchnoise/JustEnoughResources#125]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2531
- Just Enough Items (JEI) 4.8.0.114
- Just Enough Resources (JER) 0.8.6.28

Other Relevant Mods:

- MeeCreeps 0.1.3beta
- EluLib 0.1.7

#### Issue Description

When running the profile command, occasionally the game will immediately crash to desktop from a Null Pointer Exception. This is due to the fact that mods are trying to save data to JER's dummy dimension used when profiling. 

#### Issue Media

MeeCreeps
https://pastebin.com/dE6y8hjt

EluLib - Same as above just pointing to another mod in the stacktrace
```
Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at elucent.elulib.tile.CableWorldData.get(CableWorldData.java:66)
    at elucent.elulib.tile.CableManager.onWorldTick(CableManager.java:51)
```

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.

**Comment by SnowShock35** [comment]
> Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.

You're not!?! How dare you! 😜 💚
