### ISSUE TITLE
No Profiling command found

### ISSUE THREAD

**Issue by Amp1810** [way2muchnoise/JustEnoughResources#130]
Not been able to find the profiling to auto fill in the worldgen. Every time I try do use the /profile command as an opped user on a server or with cheats enabled on a single player world I get command not found.

This is for the 1.12.2 version of the mod

**Comment by way2muchnoise** [comment]
That is odd any other mods installed?

**Comment by Amp1810** [comment]
I have like around 167 other mods I'll give it a try by itself and with only a few others that add to oregen and see if it's there. But in my modpack just tells me the command isn't there

**Comment by Amp1810** [comment]
Realized my issue was in fact on my end. Seems the command can only be ran from single player worlds rather than both sp and mp. Was unaware of that fact.
