### ISSUE TITLE
Open Terrain Generator Conflict

### ISSUE THREAD

**Issue by Scrayyg** [way2muchnoise/JustEnoughResources#131]
Minecraft Version 1.12.2
Forge: 1.12.2 - 14.23.1.2555
Issue: Attempting to create a world with JER installed opens the normal world creation menu instead of the special OTG one.

**Comment by way2muchnoise** [comment]
That seems really odd, have you tried that with only JER and OTG installed (and its dependencies ofc)

**Comment by Scrayyg** [comment]
Sorry, Was sleeping. Just gave it a try, which probably should have thought to do in the first place, it does work with just JER and OTG. I also gave it another trying putting it back with my other mods and it still doesn't so I imagine that there must be some third mod that's also causing this weird interaction.

**Comment by way2muchnoise** [comment]
You'll have to find out which one, it really shouldn't be JER

**Comment by Scrayyg** [comment]
Looks like the conflict is caused by Additional Loot Tables as well. Both JER and Additional function fine with OTG individually but if they are loaded together OTG's menu won't show up.

**Comment by way2muchnoise** [comment]
So what is the smallest possible mod set that causes this? Please be specific, also list dependencies and versions.

**Comment by Scrayyg** [comment]
Smallest possible mod set.
OpenTerrainGenerator-1.12.2 - v2
OTG-Core.jar - Created by OpenTerrainGenerator
Jei_1.12.2-4.8.4.130 - Dependent for JER
JustEnoughResources-1.12.2-0.8.6.33
AdditionalLootTables-1.12.1-2.0.2.29

Also realize that AdditionalLootTables is 1.12.1 now, but until I tried using OTG I've never had a problem with it or JER in 1.12.2.

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore.
