### ISSUE TITLE
[1.12.2] NullPointerException when profiling The Betweenlands

### ISSUE THREAD

**Issue by WindFox** [way2muchnoise/JustEnoughResources#133]
In my modpack, when I try to profile the ores I get a NPE whenever it gets to The Betweenlands.

I managed to narrow it down to just that dimension by manually profiling each dimension one at a time, and that one was the only one that crashed.

[Crashlog](https://pastebin.com/q1VusrSn)

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
