### ISSUE TITLE
[1.12.2] NullPointerException in server tick loop

### ISSUE THREAD

**Issue by trienow** [way2muchnoise/JustEnoughResources#137]
# What happened
When I executed `/profile 100` in the overworld, the game crashes.

# Versions used
|  Entity   |   Version    |
|-----------|--------------|
| Minecraft |       1.12.2 |
| Forge     | 14.23.1.2555 |
| JEI       |    4.8.5.138 |
| JER       |     0.8.5.27 |

# Notes
- I've tried it with and without FoamFix, but get the same crashlog with both.
- The bug does not _seem_ to lie on chickenchunk's end, because the error still persists after removing the mod just to see what happens
- I saw you closed #116 for Minecraft **1.12**, but since the problem still seems to exist and I could not reopen the issue, I was not sure whether or not to comment on #116

# Logs
### With ChickenChunks:
[crash-2018-01-03_09.20.10-server.txt](https://github.com/way2muchnoise/JustEnoughResources/files/1599752/crash-2018-01-03_09.20.10-server.txt)
In line 9476 I execute `/profile 100`:
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/1599774/latest.log)

### Without ChickenChunks:
[crash-2018-01-03_09.57.20-server.txt](https://github.com/way2muchnoise/JustEnoughResources/files/1599831/crash-2018-01-03_09.57.20-server.txt)
In line 9591 I execute `/profile 100`:
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/1599836/latest.log)

Thanks :)

**Comment by way2muchnoise** [comment]
A+ for the report format 👍

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
