### ISSUE TITLE
can you see above y 127?

### ISSUE THREAD

**Issue by bushbaby1234** [way2muchnoise/JustEnoughResources#139]
in the deep dark the ceiling has ores and i was wondering if i could somehow pan the graph to above 127 or if it doesnt go higher.

**Comment by way2muchnoise** [comment]
As far as I know the chunk profiling should go al the way up to 256.

https://github.com/way2muchnoise/JustEnoughResources/blob/master/src/main/java/jeresources/profiling/ChunkProfiler.java#L30

**Comment by bushbaby1234** [comment]
hmm... is there a way to move the graph around?

**Comment by way2muchnoise** [comment]
Was this using data you profiled yourself?

**Comment by way2muchnoise** [comment]
Closed due to non responsive
