### ISSUE TITLE
Graph Suggestion: Blocks per Chunk

### ISSUE THREAD

**Issue by Ithronyar** [way2muchnoise/JustEnoughResources#140]
An average block count per chunk in the ore graph, accurate to 1-2 decimals. It's best if this is optional, and maybe even disabled by default. It's generally only useful for statistical analysis and ore gen testing, not average players.

**Comment by way2muchnoise** [comment]
![image](https://user-images.githubusercontent.com/5518998/42452573-b425fec0-838a-11e8-8805-1e788c79f1df.png)
