### ISSUE TITLE
Client Times out in Single Player while profiling

### ISSUE THREAD

**Issue by BrainStone** [way2muchnoise/JustEnoughResources#142]
When I start a profiling session with the command `/profile 1000 all` I randomly time out. Sometimes right at the beginning, sometimes in the middle or the end. Though it’s usually before the first 100 chunks are generated. Essentially it starts profiling a dimension and 2 minutes later I time out without any progress being displayed. I checked the RAM and it’s not being close to running out.

Here is a profiling session: https://cdn.discordapp.com/attachments/176780432371744769/440958271403065344/sampler-snapshot.nps

And the logs during that instance: https://gist.github.com/BrainStone/4fa306eaf5d00466d0a9215894440867

I used this modpack: https://minecraft.curseforge.com/projects/project-creative-modded (Version 1.2 and without Wireless Redstone, as that causes a crash (only during profiling, but that’s a WR issue))

**Comment by BrainStone** [comment]
Any updates? This is still occuring in the current versions bacsically making it impossible to create a profile...

**Comment by way2muchnoise** [comment]
Have you tried without the Twilight Forest? From the log it looks like something might be happening there.

Also sorry for the late response IRL is kinda busy for the moment.

**Comment by BrainStone** [comment]
Well I haven't though it keeps crashing at any dimension. It seems to be completely random. Sometimes it even manages to complete. (Thank god!)

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
