### ISSUE TITLE
Null Pointer Exception Crash - Wireless Redstone

### ISSUE THREAD

**Issue by docfriday11** [way2muchnoise/JustEnoughResources#143]
**Minecraft Version**: 1.12.2
**Forge Version**: 14.23.3.2670
**Just Enough Resources (JER) Version**: 0.8.7.41

Hello. When I enter the command _/profile 5 all_ the game suddenly stops doing anything and I get a crash report. I must say that the game does not close, it just stays there but I can't move or do anything.
Below I submit my crash report at pastebin.
[https://pastebin.com/dbAMvmPM](url)

**Comment by balloman** [comment]
Has anyone found a fix for this yet?

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
