### ISSUE TITLE
Null Pointer Exception Crash - Immersive Railroading

### ISSUE THREAD

**Issue by docfriday11** [way2muchnoise/JustEnoughResources#144]
Minecraft Version: 1.12.2
Forge Version: 14.23.3.2670
Just Enough Resources (JER) Version: 0.8.7.41

Hello again. This time I disabled Wireless Redstone mod and procedeed with the profiling. All went well until it reached Mars and when it started profiling, the game stopped doing anything, just froze but did not close. 
Below I submit my crash report.
[https://pastebin.com/0RXVQfWi](url)

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions. Do believe this is related to #173
