### ISSUE TITLE
World Generation add Biome restriction to manually added ores.

### ISSUE THREAD

**Issue by Axieum** [way2muchnoise/JustEnoughResources#145]
It would be nice to be able to add biome restrictions to manually added ore entries. For example, I ran a profile and on the Biomes O' Plenty gem ores, but would like to add the biome restrictions to it.

**Comment by way2muchnoise** [comment]
The whole idea behind the `world-gen.json` file is to have it generated from a scan and not user created. 
Regarding biome restrictions, extrapolating the data from a scan could result in false negatives. 
Both `Distributions` and `Restrictions` can both be used when using the API in `IWorldGenRegistry`.

Considering your PR, maybe we could add something extra. That is like a `default-world-gen.json` this file could contain an API call like structure that creates the default graphs.

**Comment by Axieum** [comment]
Understandable. I am simply trying to figure out how to appropriately graph the ore distributions for a mod such as from Biomes O' Plenty (https://github.com/Glitchfiend/BiomesOPlenty/wiki/Gem-Distribution) - as seen in their Wiki, the ores have biome restrictions and the source code suggests that they follow the same distribution as Emerald Ore (though at 12 vein count).

As seen in this issue: https://github.com/Glitchfiend/BiomesOPlenty/issues/1282.

Perhaps, a separate integration mod could resolve this?
*I did try hooking into the API and making a pull request to Biomes O' Plenty but I couldn't quite figure it out.

**Comment by Axieum** [comment]
As a side-note, you mention that the `world-gen.json` file should be generated via the `/profile` command, which is still the case should my changes be implemented; I simply added the ability to the change the distribution type from `points` to `square`/`triangular`/`underwater`. Furthermore, during the scan, the biomes are left empty and hence there should be no false negatives. I did not add any biome restriction deriving in the profiling command.

**Comment by way2muchnoise** [comment]
Changing the format of the scan file is something I would like to avoid. Adding the biomes options I would be alright with.

Making a pull into Biomes O'plenty or an integration mod would indeed be the best option.
If going for the integration approach, maybe this could be a general JER integration mod that has support for other mods next to Biomes O'plenty.

**Comment by way2muchnoise** [comment]
Closing this with reference to https://github.com/Axieum/JEROreIntegration
