### ISSUE TITLE
IskalliumReactors Mod Support

### ISSUE THREAD

**Issue by MeinKraft** [way2muchnoise/JustEnoughResources#148]
Hello

Could you please add Iskallium spawn rates/levels from the IskalliumReactors mod to the JER list?

Thank you.

**Comment by way2muchnoise** [comment]
I won't be adding support for any mods from my side.  
But there is an API avaible for modders to use, a profiling feature for mod pack developers (or users) and lately @axieum started making a mod specifically for integrations with other mods (see https://github.com/Axieum/JEROreIntegration)
