### ISSUE TITLE
[1.12.2]  Missing capability with Wizardry when attempting DIY Ore profiling via in-game command 

### ISSUE THREAD

**Issue by aking4125** [way2muchnoise/JustEnoughResources#152]
Using the /profile command in any dimension causes the game to [crash](https://paste.dimdev.org/opotuguliq.mccrash) with the following crash log. I think [this is the Wizardry mod in question](https://minecraft.curseforge.com/projects/wizardry-mod?gameCategorySlug=mc-mods&projectID=278155 ).

Not to be confused with [Electroblob's Wizardry](https://minecraft.curseforge.com/projects/electroblobs-wizardry?gameCategorySlug=mc-mods&projectID=265642). I think

[crash-2018-07-31_22.23.07-server.txt](https://github.com/way2muchnoise/JustEnoughResources/files/2247782/crash-2018-07-31_22.23.07-server.txt)

Sorry if this was already reported.

**Comment by way2muchnoise** [comment]
I would advice to also report this to the wizardry mod in question as it might be something I can't fix on my side.

**Comment by aking4125** [comment]
Gotcha. Will do.

**Comment by pau101** [comment]
Wizardry dev here, @way2muchnoise your [DummyWorld](https://github.com/way2muchnoise/JustEnoughResources/blob/d327fa6dc1b403a8482dcb7d39d7211f9c9e1641/src/main/java/jeresources/profiling/DummyWorld.java) and [FakeClientWorld](https://github.com/way2muchnoise/JustEnoughResources/blob/3bc5f72d1a37f27b0976512914c40f30f496472c/src/main/java/jeresources/util/FakeClientWorld.java) are constructed such that instances remain in an invalid state from being a capability provider which has not gone through capability initialization. In this specific case, `DummyWorld` should be overriding `has/getCapability` to delegate to the wrapped world and the `FakeClientWorld` should do this during construction:
```java
capabilities = ForgeEventFactory.gatherCapabilities(this, null);
```
