### ISSUE TITLE
Profile Command, Crash

### ISSUE THREAD

**Issue by DeadAccount76032** [way2muchnoise/JustEnoughResources#153]
Game lock'd didn't completely crash, but still gave CrashReport thankfully
(/profile 100000 all) is the command I use'd before it crashed 
[https://pastebin.com/xGdpCAD8](url)

**Comment by way2muchnoise** [comment]
Any longer crash report with some more info?

**Comment by way2muchnoise** [comment]
Closed due to non responsive
