### ISSUE TITLE
not profiling correct ore for extreme reactors

### ISSUE THREAD

**Issue by Linrox** [way2muchnoise/JustEnoughResources#154]
Yellorite is the ore block for extreme reactors but when profiling it shows as yellorium which is the dust form. and when i click on yellorite ore in NEI/JEI it does nothing, as the name is confused with the dust form.

Minecraft version:1.12.2
Forge Verison:14.23.4.2705
JEI:4.11.0.202
JER:0.8.6.28
Extreme Reactors Version:1.12.2-0.4.5.49

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
