### ISSUE TITLE
Harvestable Bedrock

### ISSUE THREAD

**Issue by tyler489** [way2muchnoise/JustEnoughResources#156]
https://gyazo.com/bb1b84c75c372002c7991bcecc2b2692 say what?

**Comment by way2muchnoise** [comment]
Which other mods do you have installed? Is this a scan you made yourself?

**Comment by tyler489** [comment]
https://pastebin.com/qiYxeD01 Possibly a custom scan. Playing Engimatica Expert mode. i dont know of any mods that make bedrock harvestable... but the pack does have flat bedrock

**Comment by way2muchnoise** [comment]
If it is a custom scan you could just remove it from the JSON. Don't know why it would list it, but to be honest I don't really care about that type of oddness in the scans.
