### ISSUE TITLE
1.12.2-0.8.10.50 dev jar on bintray is deobfuscated

### ISSUE THREAD

**Issue by Lykrast** [way2muchnoise/JustEnoughResources#159]
While trying to add JER as an optional dependency with the following lines in my build.gradle:

```
    maven {
        name = "bintray-way2muchnoise"
        url  "https://dl.bintray.com/way2muchnoise/dev/"
    }
...
    compileOnly "jeresources:JustEnoughResources-1.12.2:0.8.+"
```

The jar gradle gets is deobfuscated, despite not targeting the deobf jar. This causes errors with mismatched MCP mappings and may probably be unintended.

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, please reopen a ticket if this is still an issue.
