### ISSUE TITLE
Include Villager Trades

### ISSUE THREAD

**Issue by mezz** [way2muchnoise/JustEnoughResources#16]
Not sure if this will be possible or not, but it could be nice.

**Comment by way2muchnoise** [comment]
it would be looked into it seems quite a challenge

**Comment by Thutmose** [comment]
I would suggest waiting for forge to make it possible to add villager trades, the current system is a hardcoded set of trades and professions (hardcoded to the number vanilla adds), where only individual villagers can have them changed by editing the nbt data of the villager itself.

I sent a PR to forge for this a couple months ago (kept it updated as forge updated, so current PR is only 3 weeks old) 

Once forge accepts mine, or fixes the villager registry themselves, mods will be able to start adding trades.

the PR I sent to forge for it:
https://github.com/MinecraftForge/MinecraftForge/pull/2337

**Comment by way2muchnoise** [comment]
@mezz Could you check out the current look of the view? I don't like it that much and would love some feedback.
