### ISSUE TITLE
Problems with profiling

### ISSUE THREAD

**Issue by ReikoTigon** [way2muchnoise/JustEnoughResources#161]
Hello i made a modpack by myself. I used the command /profile 999 all and only the overworld, spectre, extrautils farming dim and the compat machines dim are profiled. The End and The Nether not. What can i do now?

**Comment by way2muchnoise** [comment]
Could provide a log?

**Comment by dragonriderworld** [comment]
There is no crash it pnly says profiling finished.

**Comment by way2muchnoise** [comment]
There still is the client and FML log

**Comment by dragonriderworld** [comment]
The problem is that only The Overworld, Spectre(RandomThings), The CompatMachines World and The ExtraUtilsQuarryDim are scanned. The Nether and The End not.

**Comment by dragonriderworld** [comment]
Oh Where can i find them

**Comment by dragonriderworld** [comment]
Another problem is that some items like wooden planks, doors, glas etc. are also shown. I think they are from villages but why are they shown there?

**Comment by dragonriderworld** [comment]
Where can i find the client and the FML log?

**Comment by way2muchnoise** [comment]
The scan is a literal representation of all blocks in the world, it will also show dirt, gravel, ...

They are in the logs folder, and the logs folder is where your mods folder is as well.

**Comment by dragonriderworld** [comment]
[2018-08-24-1.log.gz](https://github.com/way2muchnoise/JustEnoughResources/files/2318849/2018-08-24-1.log.gz)

**Comment by dragonriderworld** [comment]
[2018-08-24-2.log.gz](https://github.com/way2muchnoise/JustEnoughResources/files/2318857/2018-08-24-2.log.gz)

**Comment by dragonriderworld** [comment]
Hello im back :) 

I now have another modpack. When i go to end and nether and then go back into the overworld and start profiling it only profiles overworld and the etrautils quarry dim. Are there any issues known?

**Comment by Darinth** [comment]
I'm also running into this issue. Just running test profiling to understand it right now. I've tried the following:
Load a new world, run "/profile 500 all" and it profiles the overworld, writes data to the file and stops
Load a new world, visit the end and nether, return to overworld, run "/profile 500 all", same thing
Go to nether, run "/profile 500 all", it profiles the overworld and nether, writes data and stops.

Minecraft 1.12.2
Forge 14.23.5.2811
JER 0.8.5.27

It looks like the output is just a JSON array of blocks found, and each is dimension tagged. It is safe to just combine the arrays produced by two profilings into a single array?

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
