### ISSUE TITLE
unspecified tick lag

### ISSUE THREAD

**Issue by TimGoll** [way2muchnoise/JustEnoughResources#162]
I'm currently creating a modpack. After adding JER the game starts to lag. I don't know a specific reason, but here are some things I recognized:

- it does't lag if you are in a cave, only lags if you see the world
- if you are lover than 61 it doesn't lag either (very strange)
- in the F3 pie tick->unspecied is at about 99%
- after removing your mod everyting works as intended.
- I'm using OptiFine. And 100 other mods. Maybe there is a problem with the modcombination
- the game does not crash
- if you pause the game the tickusage goes down to a normal value, therefore the rendering isn't a problem

Minecraft 1.12.2
Forge 14.23.4.2757
JER 1.12.2-0.8.5.27

**Comment by way2muchnoise** [comment]
Sorry, but this makes no sense to me. Does this happen with only JER?

**Comment by TimGoll** [comment]
I had no time to test this. Maybe tomorrow.

**Comment by TimGoll** [comment]
Update: Removing you mod helped. But now - even without your mod - the problem suddenly arises. Even in new words.
