### ISSUE TITLE
Crash when using /profile command (cross-posted to Random Things git)

### ISSUE THREAD

**Issue by Crowfooted** [way2muchnoise/JustEnoughResources#163]
https://pastebin.com/v5uCNWW9

**Comment by way2muchnoise** [comment]
Could you link your cross post on the Random Things git? This looks like something on their end, although it might require something from me.

**Comment by Crowfooted** [comment]
Sure thing:

https://github.com/lumien231/Random-Things/issues/343

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore.
