### ISSUE TITLE
Villager Trade Levels

### ISSUE THREAD

**Issue by Robijnvogel** [way2muchnoise/JustEnoughResources#165]
It has come to my attention that this mod displays the Villager Trade Levels starting at "lv. 0", while in code they start, at least in Minecraft Forge, at `1`.

People who want to add trades using a mod, or via a CraftTweaker script, will have to do so using positive integers **higher than** 0. When they add a level 1 trade in-code, it will show as a level 0 trade in JER.
What I am talking about is the `net.minecraftforge.fml.common.registry.VillagerRegistry.VillagerCareer.addTrade` function as used [here](https://github.com/DevOnTheRocks/RockyCore/blob/master/src/main/java/rocks/devonthe/rockycore/crafttweaker/merchant/MerchantTrade.java#L47-L49).

Considering that showing the levels of trades is mostly cosmetic and the only people who will really pay attention to them will be mod developers or crafttweakeneers like me, and the displayed number in your mod doesn't match that in the code, I wondered if you could just...
Increase the displayed number by one. 😉

**Comment by bobrob2004** [comment]
Thanks. This probably explains why I'm having trouble removing villager trades in my modpack.
