### ISSUE TITLE
JER Doesn't work with the other Dimension (FTB Revelation)

### ISSUE THREAD

**Issue by Karmalefique** [way2muchnoise/JustEnoughResources#166]
Hi ! I have a problem with this mod. He show the ore generation in the overworld but not in the other dimension etc... 

Screenshoot : 
![image](https://user-images.githubusercontent.com/43883398/47226456-db3a1b00-d3c0-11e8-87b2-aa5d9ceee49a.png)

How i can fix this ?

Thank you in advance !

**Comment by way2muchnoise** [comment]
The generation data is provided using a json config file. In this case it seems like the pack author only provided it for the Overworld (or there is no diamond ore in other dimensions).

You can always make your own scan, do note that this is not super easy and requires time.
