### ISSUE TITLE
Crash running the /profile command if The Betweenlands mod is installed

### ISSUE THREAD

**Issue by enricotagliavini** [way2muchnoise/JustEnoughResources#167]
Running MC version 1.12.2 forge 1.12.2-14.23.5.2768, JER 0.8.5.27, The Betweenlands 3.3.13. I tested in Single Player world.

Removing The Betweenlands allowed me to complete the command /profile command successfully.

Crash report:
[crash-2018-10-28_20.54.24-server_tbl.txt](https://github.com/way2muchnoise/JustEnoughResources/files/2523179/crash-2018-10-28_20.54.24-server_tbl.txt)

**Comment by way2muchnoise** [comment]
Does this happen with only JER and The Betweenlands installed? (also relevant dependancies ofc).

One might think this is between BOP en The Betweenlands since the crash mentions Testworld_BOP. Although this might be something triggered by JER.

**Comment by enricotagliavini** [comment]
Good point, I didn't tried with only the two mods. My gut feeling is that is not related to BOP as this should not affect The Betweenlands dimension, however this was indeed a world generated by BOP and not a vanilla world. 

Give me some time to do a new fresh forge profile in a different directory. I'll use it for testing so I can do some test without all the noise from the other mods.

Thank you for the help :)

**Comment by enricotagliavini** [comment]
I can reproduce only with JER and TBL installed (and JEI as it's a dep of JER). No other mods, no BOP, same crash report, attached below.

The Betweeklands basically is a new dimension as far as I understand, and quite a unique one. A quick solution might simply be to ignore it for the time being, at least to avoid the crash. I'm not even sure how much JER DIY data is needed for it. I don't know much about The Betweenlands, I'm trying to avoid knowing too much about it before actually playing it not to be spoiled and have some surprise. So take this with a grain of salt :) 

[crash-2018-10-29_19.14.28-server.txt](https://github.com/way2muchnoise/JustEnoughResources/files/2526523/crash-2018-10-29_19.14.28-server.txt)

**Comment by way2muchnoise** [comment]
Do you have a cross post issue on The Betweenlands tracker? If not, could you make one? I feel like it will have to be a combined effort.

**Comment by enricotagliavini** [comment]
Done: https://github.com/Angry-Pixel/The-Betweenlands/issues/753

Thank you :)

**Comment by GoryMoon** [comment]
This has already been fixed with b61d9f15e95ea172f9d7c1c15df8d54eaecef4cd, was a capability issue with the dummy world. 0.8.9.48+ of JER have this fix from the looks of it.

**Comment by way2muchnoise** [comment]
I didn't even look at the version. Thx for confirming @GoryMoon

**Comment by enricotagliavini** [comment]
The reason I'm using version 0.8.5.27 is because it's the latest marked as "Stable" on curseforge. If you have a newer version to recommend I'll update happily.

Also, if I may, I would also advise to think about marking a newer stable release on curseforge as well. Looking at the number of downloads I'm the only conservative user of JER :)

Anyway I'm glad it's solved already, thank you!

**Comment by way2muchnoise** [comment]
The beta version should be fine, but indeed I should work on a next stable mark.
