### ISSUE TITLE
Dungeon Loot does not show every object and Entities do not render properly depending on GUI scale

### ISSUE THREAD

**Issue by sor1n** [way2muchnoise/JustEnoughResources#169]
Easier to see for yourself: https://imgur.com/a/zZtfxj8

**Comment by sor1n** [comment]
0.8.5.27

**Comment by way2muchnoise** [comment]
Could you try updating to 0.8.9.48

**Comment by sor1n** [comment]
I've tested with 0.8.9.48, nothing changed. However, I also tested with 0.8.10.50 and that seemed to have fixed the rendering issue, but loot tables only showing one item or not even an item at all hasn't been fixed.

**Comment by way2muchnoise** [comment]
Issue seems to be gone now

![image](https://user-images.githubusercontent.com/5518998/54391351-e3169680-46a4-11e9-860c-08a8be3c2bf4.png)
