### ISSUE TITLE
Unbreaking enchantment still shows in JEI when blacklisted

### ISSUE THREAD

**Issue by JadeFalcon** [way2muchnoise/JustEnoughResources#170]
https://puu.sh/C9v5y.png

https://puu.sh/C9v7y.png

**Comment by way2muchnoise** [comment]
Is it only unbreaking? Ore are the other blacklisted enchantments also still showing?

**Comment by JadeFalcon** [comment]
From what I've experimented with so far, it's only unbreaking. I have mending and vanishing blacklisted as well and that works just fine.
