### ISSUE TITLE
[Requets] Option to change the /profile command, quetsion to avoid problem

### ISSUE THREAD

**Issue by Fireztonez** [way2muchnoise/JustEnoughResources#176]
Hello,
I whant to know if you can add a simple option top change the /profile command to another command name?? I just look your issue tracker, and there have about 20 issue just about the profiling commands, I think you should just add an option, question to fix all that issue easely, and not try to fix problem mods by mods...

I get just get a crash on my modpack when I try to do the famous /profile, but i'm not sure yet is caused my incompatibility with what mod... I have to look more, but I really, if you can just add this option, it should be nice!!

https://gist.github.com/Fireztonez/bc03f586dd34c360d4efd712ac37a5c6

**Comment by way2muchnoise** [comment]
I don't exactly understand what you are asking for:  
Changing the command name or create some magic code that fixes all issues with other mods?  
Cause I'm fairly certain I'm not a wizard.

**Comment by way2muchnoise** [comment]
Command name changed to `jer_profile` in 3eb975ffb950de4189b7ecb834e804dd9c4ab9ae
