### ISSUE TITLE
Configurable block blacklist

### ISSUE THREAD

**Issue by TheDeviantCrafter** [way2muchnoise/JustEnoughResources#179]
There are a lot of blocks that show up in JER that aren't particularly useful. Dozens of leaf and log blocks, blocks that generate in structures, etc. I'd like to be able to blacklist specific blocks so they don't appear in JEI after profiling.

I could manually remove them, but I plan to re-profile the game every time I change worldgen. Since it currently creates a 1.7 megabyte file in my pack, this isn't very practical.

**Comment by way2muchnoise** [comment]
Blacklist coming soon, [see wiki for info](https://github.com/way2muchnoise/JustEnoughResources/wiki/Profiling). Committed in 4c8786c7a85239d3260a2c5e462c6c15c252275a
