### ISSUE TITLE
JER tabs not showing up

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [way2muchnoise/JustEnoughResources#180]
JER is installed and profiling works fine, but for some reason, the tabs do not show up. There's no crash report.

Using JustEnoughResources-1.12.2-0.9.0.52 (latest alpha at the moment)

This is the log found in logs folder:
[2019-03-11-1.log.gz](https://github.com/way2muchnoise/JustEnoughResources/files/3014454/2019-03-11-1.log.gz)

This is the latest log:
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/3014465/latest.log)

I don't know what other information I should provide.

**Comment by way2muchnoise** [comment]
Crash from the provided log file

`[18:01:20] [Client thread/ERROR]: Failed to register mod plugin: class jeresources.jei.JEIConfig
net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: itemWeight
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:210) ~[forge-1.12.2-14.23.5.2811-universal.jar:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:106) ~[ObfuscationReflectionHelper.class:?]
	at jeresources.util.SeedHelper.getSeeds(SeedHelper.java:22) ~[SeedHelper.class:?]`

**Comment by triasinformatica-gabe** [comment]
I'm experiencing the same issue (same error) using Just Enought Resources version 1.12.2-0.9.0.52 included in the [Enigmatica 2 Expert](https://minecraft.curseforge.com/projects/enigmatica2expert) modpack version 1.59a. I've seen users in let's play series using the tabs a few months ago using an older version of the pack. Version 1.59a of this modpack is using Forge forge-14.23.5.2781.

My own modpack using JER version 1.12.2-0.8.9.48 on Forge 14.23.5.2800 does not have this error.

Don't know if this helps narrowing down the issue a bit further; but this is the info I could find. If there's  anything more I can do to help find the cause; let me know.

**Comment by way2muchnoise** [comment]
Using some newer functions in forge, version 14.23.5.2779 or above is now required.
