### ISSUE TITLE
/Profile Causes Crash Exception In Server Tick Loop

### ISSUE THREAD

**Issue by IceArrow04** [way2muchnoise/JustEnoughResources#182]
Immediately after entering /profile (#ofchunks) all, my game freezes for a second or two then crashes

Here's the crash log https://pastebin.com/0CY90tEQ

**Comment by way2muchnoise** [comment]
Cross mod with Yabba
` com.latmod.yabba.YabbaEventHandler.tickServerWorld(YabbaEventHandler.java:130)`

**Comment by LatvianModder** [comment]
`BarrelNetwork.get(event.world).tick();` which should always be non-null, since its a capability that's attached to world. How is it possible to be null in this case?

**Comment by way2muchnoise** [comment]
Not exactly sure, why it would be causing a null there. We do create a DummyWorld and something might go wrong there. It could also be any other mod in the list causing some weird onTick event.

@IceArrow04 could you try with just Yabba and JER?

@LatvianModder I'll check if there is something I'm missing (might contact you on Discord to figure this one ou)

**Comment by IceArrow04** [comment]
Alright after testing with just YABBA and JER (and their respective dependencies) there seems to be no issues with the /profile command so I'm not sure what's up.
Here's my full mod list if it's of any help
https://ftb.gamepedia.com/FTB_Ultimate_Reloaded

**Comment by LatvianModder** [comment]
I "fixed" it on my end (added nullcheck) so latest yabba will not error

**Comment by way2muchnoise** [comment]
Think adding that null check is the best "fix", considering it doesn't happen with just YABBA and JER. Some other mod must trigger the crash causing tick.
