### ISSUE TITLE
Dim not named when profiling

### ISSUE THREAD

**Issue by BubbaVB** [way2muchnoise/JustEnoughResources#184]
I'm creating my own mod pack.  In it I'm using JER version JustEnoughResources-1.12.2-0.9.0.53.  When I run the profile it displays the Dim name while the profiling is taking place.  But after you relaunch the game to see the results in JEI.  The Dim is only labeled with a number.  The exception to this is the overworld.  Below are some examples from the world-gen.json file.

"dim": "Dim 0: overworld"
"dim": "Dim 51: 51"
"dim": "Dim -6: -6"
"dim": "Dim -11325: -11325"

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
