### ISSUE TITLE
Gold Ore Generation Graphs do not show proper biome information from 1.10 onward

### ISSUE THREAD

**Issue by DoomRater** [way2muchnoise/JustEnoughResources#191]
In versions of Minecraft 1.10 and beyond, gold ore also spawns in additional ranges in mesa biomes.  JER does not report this oregen range in its report.  Tested in 1.12.2 builds, but as noted this was added in 1.10 and remains true in current versions of Minecraft.

**Comment by way2muchnoise** [comment]
The default graphs are based on information I found on the minecraft wiki back when I started the mod. Feel free to link me the new info and I'll update.

**Comment by DoomRater** [comment]
https://minecraft.gamepedia.com/Badlands
 In the patch notes in 1.10, it's noted that in 16w20a that "The normal 2 veins of gold ore below Y=32 in mesas will now attempt to generate 20 veins at elevations between 32 and 79" in a Mesa Biome.
1.13 and beyond they're called Badlands, but the gold ore generation remains the same.  As you can see, they're loaded with gold.
