### ISSUE TITLE
Profiling individual dimensions clobbers data for other dimensions

### ISSUE THREAD

**Issue by maladaptly** [way2muchnoise/JustEnoughResources#193]
1. /tpx 0 0 256 0
2. /jer_profile xxxx
3. Restart Minecraft
4. /tpx -1 0 256 0
5. /jer_profile xxxx

world-gen.json now contains ONLY data for the Nether, even though overworld data was loaded and available to be re-saved.

**Comment by maladaptly** [comment]
The obvious workaround of profiling all dimensions in one go is not possible for some configurations (see #192)

**Comment by way2muchnoise** [comment]
This is currently a limitation, might add a param to combine the loaded config with the new scan. Although currently kinda busy with life and updating to 1.14. So it might only be available in the next versions.
