### ISSUE TITLE
Suggestion: Ore gen graphs should display ores from mods and other dimensions as well as which dimensions they are found etc.

### ISSUE THREAD

**Issue by SirAron111** [way2muchnoise/JustEnoughResources#195]
Suggestion: Ore gen graphs should display ores from mods and other dimensions as well as which dimensions they are found etc.

ATM the ore generation graph doesn’t show at all for most ores from other dimensions or mods like abyssal craft, the between lands, the midnight and many more. Or even mods that dont add dimensions but have like 1 or 2 special ores.
Isnt there a way to make the ore graph get its data from the ore dictionary? and look for where they generate?

**Comment by way2muchnoise** [comment]
There is a command (/jer_profile, /profile in older versions) to scan the generated terrain and generate graphs (you only need to do this once). This can be used by pack makers (to be included in the pack) or individual players. The handling differs to much for each mod that writing something generic is going to be either utterly complex or ridiculously hacky.
