### ISSUE TITLE
NPE from FakeClientWorld

### ISSUE THREAD

**Issue by LuminescentMoon** [way2muchnoise/JustEnoughResources#197]
[FakeClientWorld](https://github.com/way2muchnoise/JustEnoughResources/blob/1ca83769a2ee4d439b8fdda422b98677ebd6c929/src/main/java/jeresources/util/FakeClientWorld.java) does not initialize `World.mapStorage` field, leading to unexpected NPEs when other mods try to use the result of `World.getMapStorage`.

One solution would be to initialize `mapStorage` before [calling ForgeEventFactory.gatherCapabilities](https://github.com/way2muchnoise/JustEnoughResources/blob/1ca83769a2ee4d439b8fdda422b98677ebd6c929/src/main/java/jeresources/util/FakeClientWorld.java#L43v). Note that an access transformer is necessary as `World.mapStorage` is marked `protected`.

Related issues from StellarSky:

- https://github.com/MinecraftModDevelopmentMods/StellarSky/issues/104
- https://github.com/MinecraftModDevelopmentMods/StellarSky/issues/113
- https://github.com/MinecraftModDevelopmentMods/StellarSky/issues/115

**Comment by way2muchnoise** [comment]
Will have to rewrite profiling for newer versions, leaving this open as a reminder.

**Comment by way2muchnoise** [comment]
Closing old version issues, profiling needs to be rewritten for 1.19+ anyways
