### ISSUE TITLE
JEI and JER crash

### ISSUE THREAD

**Issue by adran06** [way2muchnoise/JustEnoughResources#198]
https://paste.dimdev.org/xoladirife.mccrash Here's a copy of the error. Don't know what it means. Just know it's caused by JEI and JER.

**Comment by way2muchnoise** [comment]
Allocate more RAM 3 gigs is not enough for a pack with almost 200 mods. See exception generated `java.lang.OutOfMemoryError: GC overhead limit exceeded`.
