### ISSUE TITLE
Crashes/freezes while profiling.

### ISSUE THREAD

**Issue by Silgon85** [way2muchnoise/JustEnoughResources#199]
So far I have tried to profile all dims, than just the overworld. Tried just 1 chuck up to 100 chunks. Still crashes, When it freezes I have left it alone for 8+ hours on profiling overword 1 chunk. I have looked into everything I can do, and still the issue persists. I have included the latest crash, I still have more if they need to be looked at.
[crash-2019-08-26_14.47.25-client.txt](https://github.com/way2muchnoise/JustEnoughResources/files/3552286/crash-2019-08-26_14.47.25-client.txt)

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
