### ISSUE TITLE
Profiling does not appear to be working properly

### ISSUE THREAD

**Issue by Zygus42** [way2muchnoise/JustEnoughResources#200]
JustEnoughResources-1.12.2-0.9.2.60
ImmersiveEngineering-0.12-89
jei_1.12.2-4.15.0.289
forge-1.12.2-14.23.5.2838-installer-win

This is the file created by /jer_profile 1000:
[world-gen.json.txt](https://github.com/way2muchnoise/JustEnoughResources/files/3557175/world-gen.json.txt)

There is no mention of copper from immersive engineering, and yet as you can see i'm standing on it:
![2019-08-30_04 08 55](https://user-images.githubusercontent.com/20757445/63972928-4aea5d80-cadc-11e9-838f-a3ed3b5296f8.png)

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
