### ISSUE TITLE
JER_profile Crash with H&CMod

### ISSUE THREAD

**Issue by iamweirdie** [way2muchnoise/JustEnoughResources#201]
Hello,

I ran a JER_profile in my single player world and the game crashed. Twice.

[crash-2019-09-12_01.01.23-server.txt](https://github.com/way2muchnoise/JustEnoughResources/files/3608244/crash-2019-09-12_01.01.23-server.txt)
[crash-2019-09-12_19.18.16-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/3608211/crash-2019-09-12_19.18.16-server.txt)

This was with
forge-1.12.2-14.23.5.2838-universal.jar
HeatAndClimateLib_1.12.2-3.1.1.jar 
HeatAndClimateMod_1.12.2-3.1.3.jar
jei_1.12.2-4.15.0.268.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
JEROreIntegration-1.12.2-1.1.0.jar

There are other mods on the list, but i thought these might be the most relevant.

https://github.com/defeatedcrow/HeatAndClimateMod/issues/125
i have also sent the other author this issue to be safe.

**Comment by iamweirdie** [comment]
Update: It's not HaCl mod's fault.
Still trying to find cause.

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore.
