### ISSUE TITLE
[Feature Request] [1.12.2] Lycanites Mobs and Fire and Ice integration 

### ISSUE THREAD

**Issue by Agret-Brisignr** [way2muchnoise/JustEnoughResources#202]
They're large mods with a lot of mobs, especially Lycanites, but it would be nice to have these integrated without having to scrounge the .json's of each mob.

**Comment by way2muchnoise** [comment]
In 1.12 this isn't doable in a clean way, however with the changes in 1.14 this will be possible. Also related to #150 and #107

**Comment by way2muchnoise** [comment]
Closing this, but leaving the tickets mentioned open to centralise.
