### ISSUE TITLE
Please support 1.14.4 (Forge)

### ISSUE THREAD

**Issue by SepSol** [way2muchnoise/JustEnoughResources#203]
Any plans?

**Comment by way2muchnoise** [comment]
Working on it, getting there.

**Comment by SepSol** [comment]
Yaaay :D

**Comment by way2muchnoise** [comment]
Here you go d04c9a4a12dda05348a3397144cc885714ee89a4, send quite some time on it behind the scenes ;)

**Comment by SepSol** [comment]
Wow! That is lots of code :D Thanks a lot!
