### ISSUE TITLE
mod incompat jei/jer with ultimate car mod villager(1.14.4) forge

### ISSUE THREAD

**Issue by SDUBZ** [way2muchnoise/JustEnoughResources#206]
https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod/issues/89

All info and logs etc are given above

**Comment by way2muchnoise** [comment]
Link to client log: http://puu.sh/EBJon/0385b4ec29.log

**Comment by way2muchnoise** [comment]
Closing as I can no longer access the original issue.
