### ISSUE TITLE
[1.14.4] Confusion re JERAPI

### ISSUE THREAD

**Issue by noobanidus** [way2muchnoise/JustEnoughResources#207]
As far as I can tell, I can't work out at which point it's actually safe to call the "init" function that was previously used to register a variety of things via the JERAPI. 

Due to the nature of mods loading asynchronously I've become pretty confused about when and where it's safe to trigger this -- or if the JERAPI annotation is actually injecting anything at all.

Clarification at any point would be great :)

**Comment by way2muchnoise** [comment]
Not sure myself atm, will check

**Comment by way2muchnoise** [comment]
Is this still a question?
