### ISSUE TITLE
Issues with multi world display

### ISSUE THREAD

**Issue by mezz** [way2muchnoise/JustEnoughResources#21]
Now that we have data from dimensions working (when the PR for #19 is pulled), we need to display it well.
Currently, things are very strange looking.  
* [x] For instance gravel, there are two entries and one of the entries has all the drops repeated.
* [ ]  combine data from all dimensions and list the exact dimension names somewhere (tooltip?)
* [x] drops are not ordered by drop chance any more, 
* [x]  some drops display an average of 1 higher in the tooltip than the stack number on them.

**Comment by way2muchnoise** [comment]
I fixed quite some things in 0002f0f029e22ae0f6a4a5f8b8bf27b4486b32dc

**Comment by way2muchnoise** [comment]
The tooltip already show valid dimensions (or wasn't this what you had in mind?)
![](http://puu.sh/mGPp7/f5ce24d447.png)

**Comment by way2muchnoise** [comment]
I think the last one on the list is also fixed but not 100% certain.

**Comment by mezz** [comment]
Looks like you fixed most of the issues :)
I think since the dimension pages are separate, the valid dimension should be listed above the graph.
I'm going to move silk touch and dimension to display on the page instead of the tooltip and see how it  looks.

**Comment by mezz** [comment]
I think that with your fixes plus this PR https://github.com/way2muchnoise/JustEnoughResources/pull/25 everything looks fine.
