### ISSUE TITLE
[1.14.4-0.10.0.66] Graph doesn't display Y level on mouseover

### ISSUE THREAD

**Issue by trevorjd** [way2muchnoise/JustEnoughResources#211]
The world gen graph has only 3 y-levels, 0, 63 and 127. Mousing over the graph line doesn't show the current level, as it did in previous versions.

I can only guess from these images that my world gen is a bit screwy...
Diamond looks normal https://i.imgur.com/PvttVxE.png
but Lapis doesn't! https://i.imgur.com/cA4VRdv.png

It was trying to estimate where that peak is on the Lapis graph that brought me here.

As a side-note, this version isn't giving results for modded ores, but I'm sure that's just due to limited time and energy. Thanks!

**Comment by way2muchnoise** [comment]
Not showing on mouse over is for use a bug. The modded ores used to be done by pack makers with the profiling feature. Which currently isn't fully ported, but I'm also having a look whether it is possible to do it differently since 1.14+

**Comment by YourSouLi5Mine** [comment]
I have the same problem regarding the mouse hover in 1.14.4. I'm not really good at Java but if there is anything I could do to help fix the bug I'll be glad to help
