### ISSUE TITLE
Missing plant drop: "Beetroot" - JustEnoughResources-1.14.4-0.10.0.66

### ISSUE THREAD

**Issue by UncleSam139** [way2muchnoise/JustEnoughResources#213]
Hi, only 5 plants are supported in vanilla Minecraft.

1. Carrot, 2. Potato, 3. Wheat, 4. Melon and 5. Pumpkin. But there is the 6th Beetroot, and this is not included in the "Plant Drops". Can you add the missing plant, please?

And one other thing I have noticed is, under Dungeon Drops the one drop only shows the path not the name. I don't know if this is a bug, but maybe you can fix it.

Path: "dungeon/village/village_desert_house"

Thanks for your hard work and making/porting this fantastic mod for us.

**Comment by way2muchnoise** [comment]
#216 fixes the desert house thing, will checkout and likely merge #215 which addresses the other points

**Comment by way2muchnoise** [comment]
Fixed in #215
