### ISSUE TITLE
NoSuchFieldError when loading world

### ISSUE THREAD

**Issue by CoffeeCatRailway** [way2muchnoise/JustEnoughResources#218]
I'm using the API in my mod and I get the error below when I enter a world even if I'm not calling anything from the API
```
[13:45:51] [Client thread/ERROR] [me.je.lo.PluginCaller/]: Caught an error from mod plugin: class jeresources.jei.JEIConfig minecraft:jeresources
java.lang.NoSuchFieldError: field_221239_a
```

I did some poking around and found the error is in ` jeresources.util.VillagersHelper.getTrades` when you try to call `net.minecraft.entity.merchant.villager.VillagerTrades.VILLAGER_DEFAULT_TRADES`
I'm using forge `1.14.4 - 28.1.111` and mappings `20191109-1.14.3`

Hope this helps!

**Comment by way2muchnoise** [comment]
What is ```me.je.lo.PluginCaller```? What other mods do you have installed in your env?

**Comment by CoffeeCatRailway** [comment]
Filters by MrCrayfish - client side
jei
the one probe
jer - :)

thats it

**Comment by way2muchnoise** [comment]
Will check

**Comment by way2muchnoise** [comment]
Closing old version issues
