### ISSUE TITLE
[1.14.4] Profile & DIY Data

### ISSUE THREAD

**Issue by NielsPilgaard** [way2muchnoise/JustEnoughResources#219]
Hello! 
Do you plan to re-implement the `/jer_profile` feature in 1.14.4? Oregen graphs were really nice :)

**Comment by way2muchnoise** [comment]
It is indeed the plan, just need to find the time :P

**Comment by NillerMedDild** [comment]
Awesome, thanks for the quick response!

**Comment by Tander** [comment]
+1, I'd like to use this feature.

**Comment by way2muchnoise** [comment]
As an FYI (dunno if it can helps), you can use profiling data from older version and import it.
e.g. Run profiling in 1.13 and import in 1.14+ (might be interesting to some)

**Comment by way2muchnoise** [comment]
Closing old version issues, profiling needs to be rewritten for 1.19+ anyways
