### ISSUE TITLE
Upgrade Aquatic disables some tabs

### ISSUE THREAD

**Issue by IronPiston** [way2muchnoise/JustEnoughResources#221]
JER Version: 1.14.4-0.10.0.70
Upgrade-Aquatic Version: 1.4.5

When installed, Upgrade Aquatic seems to disable these tabs:
- Plant drops
- World Gen
- Mob drops
- Dungeon Chests  

Does this happen because Upgrade Aquatic adds mobs, loot, and other world gen?

![image](https://user-images.githubusercontent.com/11603684/72011260-0fe0ff00-321f-11ea-9aee-bcf7bf0c6c3a.png)

**Comment by way2muchnoise** [comment]
Could you post a log from client startup?

**Comment by IronPiston** [comment]
[Here is the log](https://paste.ee/p/KNhT7)

**Comment by way2muchnoise** [comment]
Related to #223

**Comment by way2muchnoise** [comment]
Can you test with [JustEnoughResources-1.14.4-0.10.1.76](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/2914259)

**Comment by IronPiston** [comment]
![Screenshot from 2020-03-28 20-08-00](https://user-images.githubusercontent.com/11603684/77837536-e3f35c80-712f-11ea-8427-90fc83ca412b.png)

This fixes the issue, thanks!
