### ISSUE TITLE
[1.14.4] JER only has Villager Trades

### ISSUE THREAD

**Issue by NillerMedDild** [way2muchnoise/JustEnoughResources#227]
None of JER's JEI integrations work, besides Villager Trades - I'm not sure if it's a bug, or just stuff that hasn't been ported yet?

### Versions
- jei-1.14.4-6.0.0.27
- JustEnoughResources-1.14.4-0.10.0.70

Original issue: https://github.com/NillerMedDild/Enigmatica4/issues/293

**Comment by way2muchnoise** [comment]
Related to #223 , hope to find some time over the weekend to fix.

**Comment by NillerMedDild** [comment]
Cool, no rush though, I just wanted to know for sure :)

**Comment by way2muchnoise** [comment]
Can you test with [JustEnoughResources-1.14.4-0.10.1.76](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/2914259)

**Comment by NillerMedDild** [comment]
That works, thanks! 
Villagers still only have 1 page maximum per villager type, but that's minor.
