### ISSUE TITLE
[1.12.2] crash on generating profile in freshly created local world without moving

### ISSUE THREAD

**Issue by kaliisteele** [way2muchnoise/JustEnoughResources#228]
any attempt to generate a profile with a value greater then 1 causes a crash 
https://paste.dimdev.org/toqaqidobe.mccrash

**Comment by Mrthomas20121** [comment]
im getting the same error. it also corrupt my world for some reason.

**Comment by way2muchnoise** [comment]
Cannot reach the crash log link any more, feel free to create a new issue if this still occurs
