### ISSUE TITLE
[1.14.4] Client crash while looking at some PneumaticCraft: Repressurized entity on the mob drops page

### ISSUE THREAD

**Issue by PokeMaserJ** [way2muchnoise/JustEnoughResources#232]
I was just gong though the mob drop page from JER, my client crashed while I was trying to look at a PneumaticCraft: Repressurized entity,  from looking at the crash log. I saw some entities in JER from PneumaticCraft: Repressurized w/o crashing, , so it appears to be a certain one that crashes. I can cross post if needed.
https://pastebin.com/DGf1M1Vm
pneumaticcraft-repressurized-1.14.4-1.0.0-8.jar
JustEnoughResources-1.14.4-0.10.1.76

**Comment by way2muchnoise** [comment]
Closing old version issues
