### ISSUE TITLE
JER 1.12.2 (0.9.2.60) only showing Vanilla oregen and mobdrops

### ISSUE THREAD

**Issue by Gargemel** [way2muchnoise/JustEnoughResources#234]
Mod list below showing all versions...
Not sure how to fix the mob file!

If I run the JER command it crashes and blames Stellar Sky for it (crashreport):

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2020-04-24 11:49:51 CEST
Description: Exception in server tick loop

java.lang.NullPointerException
    at stellarium.stellars.StellarManager.getManager(StellarManager.java:43)
    at stellarium.StellarTickHandler.tickStart(StellarTickHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_999_StellarTickHandler_tickStart_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2361012616 bytes (2251 MB) / 6168248320 bytes (5882 MB) up to 6168248320 bytes (5882 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144M -Xms6144M
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 106 mods loaded, 106 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                  | Version                  | Source                                             | Signature                                |
       |:------ |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | forge               | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
       | LCHIJA | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
       | LCHIJA | micdoodlecore       |                          | minecraft.jar                                      | None                                     |
       | LCHIJA | obfuscate           | 0.4.2                    | minecraft.jar                                      | None                                     |
       | LCHIJA | ic2                 | 2.8.73-ex112             | industrialcraft-2-2.8.73-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHIJA | jei                 | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                          | None                                     |
       | LCHIJA | twilightforest      | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
       | LCHIJA | tconstruct          | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LCHIJA | galacticraftcore    | 4.0.2.252                | GalacticraftCore-1.12.2-4.0.2.252.jar              | None                                     |
       | LCHIJA | galacticraftplanets | 4.0.2.252                | Galacticraft-Planets-1.12.2-4.0.2.252.jar          | None                                     |
       | LCHIJA | asmodeuscore        | 0.0.13                   | AsmodeusCore-1.12.2-0.0.13.jar                     | None                                     |
       | LCHIJA | backpack            | 3.0.2                    | backpack-3.0.2-1.12.2.jar                          | None                                     |
       | LCHIJA | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | bdsandm             | 0.0.24                   | BarrelsDrumsStorageAndMore-0.0.24.jar              | None                                     |
       | LCHIJA | crafttweaker        | 4.1.20                   | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
       | LCHIJA | base                | 3.13.0                   | base-1.12.2-3.13.0.jar                             | None                                     |
       | LCHIJA | bdlib               | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
       | LCHIJA | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | LCHIJA | betterquesting      | 3.5.300                  | BetterQuesting-3.5.300.jar                         | None                                     |
       | LCHIJA | bibliocraft         | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | buildcraftlib       | 7.99.17                  | buildcraft-core-7.99.17.jar                        | None                                     |
       | LCHIJA | buildcraftcore      | 7.99.17                  | buildcraft-core-7.99.17.jar                        | None                                     |
       | LCHIJA | buildcraftenergy    | 7.99.17                  | buildcraft-energy-7.99.17.jar                      | None                                     |
       | LCHIJA | forestry            | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                      | None                                     |
       | LCHIJA | binniecore          | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                   | None                                     |
       | LCHIJA | binniedesign        | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                   | None                                     |
       | LCHIJA | genetics            | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                   | None                                     |
       | LCHIJA | botany              | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                   | None                                     |
       | LCHIJA | extrabees           | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                   | None                                     |
       | LCHIJA | extratrees          | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                   | None                                     |
       | LCHIJA | biomesoplenty       | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar      | None                                     |
       | LCHIJA | bookshelf           | 2.3.557                  | Bookshelf-1.12.2-2.3.557.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | codechickenlib      | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux        | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | brandonscore        | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | LCHIJA | buildcraftbuilders  | 7.99.17                  | buildcraft-builders-7.99.17.jar                    | None                                     |
       | LCHIJA | buildcrafttransport | 7.99.17                  | buildcraft-transport-7.99.17.jar                   | None                                     |
       | LCHIJA | buildcraftcompat    | 7.99.14                  | buildcraft-compat-7.99.14.jar                      | None                                     |
       | LCHIJA | buildcraftfactory   | 7.99.17                  | buildcraft-factory-7.99.17.jar                     | None                                     |
       | LCHIJA | cfm                 | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                             | None                                     |
       | LCHIJA | contenttweaker      | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                    | None                                     |
       | LCHIJA | conarm              | 1.2.5.4                  | conarm-1.12.2-1.2.5.4.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | ctgui               | 1.0.0                    | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
       | LCHIJA | crafttweakerjei     | 2.0.3                    | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
       | LCHIJA | customspawner       | 3.11.4                   | CustomMobSpawner-3.11.4.jar.zip                    | None                                     |
       | LCHIJA | customnpcs          | 1.12                     | CustomNPCs_1.12.2(13may18).jar                     | None                                     |
       | LCHIJA | draconicevolution   | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LCHIJA | mocreatures         | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar.zip            | None                                     |
       | LCHIJA | elevatorid          | 1.3.11                   | ElevatorMod-1.12.2-1.3.11.jar                      | None                                     |
       | LCHIJA | enderstorage        | 2.4.3.131                | EnderStorage-1.12.2-2.4.3.131-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | golems              | 7.1.9                    | ExtraGolems-1.12-7.1.9.jar                         | None                                     |
       | LCHIJA | mjrlegendslib       | 1.12.2-1.1.9             | MJRLegendsLib-1.12.2-1.1.9.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | zollerngalaxy       | 2.0.13                   | ZollernGalaxy-1.12.2-v2.0.14.jar                   | None                                     |
       | LCHIJA | extraplanets        | 1.12.2-0.6.3             | ExtraPlanets-1.12.2-0.6.3.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | fastleafdecay       | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | LCHIJA | galacticrafttweaker | 1.12.2-1.0.3             | GalacticraftTweaker-1.12.2-1.0.3.jar               | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | galaxyspace         | 2.0.12                   | GalaxySpace-1.12.2-2.0.12.jar                      | None                                     |
       | LCHIJA | gendustry           | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                     | None                                     |
       | LCHIJA | gendustryjei        | 1.0.2                    | gendustryjei-1.0.2.jar                             | None                                     |
       | LCHIJA | placebo             | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
       | LCHIJA | hexxitgear          | 2.8.0                    | Hexxit+Gear-1.12.2-2.8.0.jar                       | None                                     |
       | LCHIJA | icbmclassic         | 1.12.2-3.3.0.63          | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
       | LCHIJA | ichunutil           | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
       | LCHIJA | infernalmobs        | 1.7.5                    | InfernalMobs-1.12.2.jar                            | None                                     |
       | LCHIJA | instantunify        | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                      | None                                     |
       | LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest           | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                    | None                                     |
       | LCHIJA | jeibees             | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
       | LCHIJA | journeymap          | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
       | LCHIJA | jeresources         | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
       | LCHIJA | magicbees           | 1.0                      | MagicBees-1.12.2-3.1.10.jar                        | None                                     |
       | LCHIJA | mcjtylib_ng         | 3.0.4                    | mcjtylib-1.12-3.0.4.jar                            | None                                     |
       | LCHIJA | moreplanets         | 2.0.22                   | More-Planets-1.12.2-2.0.22-GC238.jar               | b3468b224a74e296555ad7efeb35f482e6f445de |
       | LCHIJA | neid                | 1.5.4.4                  | NotEnoughIDs-1.5.4.4.jar                           | None                                     |
       | LCHIJA | packingtape         | 0.7.6                    | PackingTape-1.12.2-0.7.6.jar                       | None                                     |
       | LCHIJA | brewcraft           | 1.12.2-1.0.1             | Pam's+BrewCraft+1.12.2-1.0.1.jar                   | None                                     |
       | LCHIJA | harvestcraft        | 1.12.2y                  | Pam's+HarvestCraft+1.12.2y.jar                     | None                                     |
       | LCHIJA | planetprogression   | 1.12.2-0.4.2             | PlanetProgression-1.12.2-0.4.2.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | portalgun           | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                         | None                                     |
       | LCHIJA | projectintelligence | 1.0.9                    | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
       | LCHIJA | reccomplex          | 1.4.7                    | RecurrentComplex-1.4.7.jar                         | None                                     |
       | LCHIJA | rftools             | 7.55                     | rftools-1.12-7.55.jar                              | None                                     |
       | LCHIJA | rftoolsdim          | 5.60                     | rftoolsdim-1.12-5.60.jar                           | None                                     |
       | LCHIJA | signpost            | 1.06.1                   | signpost-1.12-1.06.1.jar                           | None                                     |
       | LCHIJA | soulshardstow       | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                   | None                                     |
       | LCHIJA | spaceambient        | 0.0.1                    | SpaceAmbient-1.12.2-0.0.1.jar                      | None                                     |
       | LCHIJA | stellarapi          | 1.12.2-0.4.2.9           | Stellar+API-1.12.2-0.4.2.9.jar                     | None                                     |
       | LCHIJA | stellarsky          | 1.12.2-0.5.2.8           | Stellar+Sky-1.12.2-0.5.2.8.jar                     | None                                     |
       | LCHIJA | subcommonlib        | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
       | LCHIJA | taiga               | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                             | None                                     |
       | LCHIJA | golems_tcon         | 7.1.5-0                  | TinkersGolemsAddon-1.12-7.1.5-0.jar                | None                                     |
       | LCHIJA | tinkersjei          | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
       | LCHIJA | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | LCHIJA | bspkrscore          | at_0.9                   | Treecapitator-1.12-at_0.9a.jar                     | None                                     |
       | LCHIJA | treecapitator       | at_0.9                   | Treecapitator-1.12-at_0.9a.jar                     | None                                     |
       | LCHIJA | vanillafix          | 1.0.10-150               | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCHIJA | varodd              | 3.1                      | varodd-1.12.2-3.1.jar                              | None                                     |
       | LCHIJA | vehicle             | 0.43.4                   | vehicle-0.43.4-mc1.12.2.jar                        | None                                     |
       | LCHIJA | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | LCHIJA | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | LCHIJA | wanionlib           | 1.12.2-2.4               | WanionLib-1.12.2-2.4.jar                           | None                                     |
       | LCHIJA | unidict             | 1.12.2-2.9.6             | UniDict-1.12.2-2.9.6.jar                           | None                                     |
  Loaded coremods (and transformers): Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.252.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      GSHooksLoader (GalaxySpace-1.12.2-2.0.12.jar)
                                        galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  List of loaded APIs: * Base|API (1.0.0) from base-1.12.2-3.13.0.jar
                       * BetterQuesting|API (3.2) from BetterQuesting-3.5.300.jar
                       * BetterQuesting|API2 (3.1) from BetterQuesting-3.5.300.jar
                       * BuildCraftAPI|blocks (1.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|boards (2.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|core (2.2) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|crops (1.1) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|enums (1.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|events (2.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|facades (1.1) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|filler (5.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|fuels (2.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|gates (4.1) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|items (1.1) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|library (2.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|lists (1.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|power (1.3) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|recipes (3.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|robotics (3.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|statements (1.1) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|tiles (1.2) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|tools (1.0) from buildcraft-core-7.99.17.jar
                       * BuildCraftAPI|transport (5.0) from buildcraft-core-7.99.17.jar
                       * Core (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Blocks (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Constants (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Entities (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Entities|Data (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Entities|Data|Role (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Events (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Handlers (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * Core|Handlers|Data (0.1) from CustomNPCs_1.12.2(13may18).jar
                       * DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.25.351-universal.jar
                       * ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.322.jar
                       * ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.322.jar
                       * Galacticraft API (1.0) from GalacticraftCore-1.12.2-4.0.2.252.jar
                       * gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
                       * iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
                       * jeresources|API (0.9.2.60) from JustEnoughResources-1.12.2-0.9.2.60.jar
                       * journeymap|client-api (1.4) from journeymap-1.12.2-5.7.1.jar
                       * journeymap|client-api-display (1.4) from journeymap-1.12.2-5.7.1.jar
                       * journeymap|client-api-event (1.4) from journeymap-1.12.2-5.7.1.jar
                       * journeymap|client-api-model (1.4) from journeymap-1.12.2-5.7.1.jar
                       * journeymap|client-api-util (1.4) from journeymap-1.12.2-5.7.1.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.293.jar
                       * stellarapi|api (1.12.2-0.4.2.9) from Stellar+API-1.12.2-0.4.2.9.jar
                       * veinminerApi (0.3) from VeinMiner-1.12-0.38.2.647+b31535a.jar
                       * WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
  Suspected Mods: Stellar Sky (stellarsky)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Gargemel'/5362, l='New World', x=223.85, y=73.00, z=229.89]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

All info in the pictures below!
![Github1](https://user-images.githubusercontent.com/63905653/80200022-53bb1100-8622-11ea-9c13-53c9c564d9a9.JPG)
![Github2](https://user-images.githubusercontent.com/63905653/80200027-54ec3e00-8622-11ea-9581-d1727b523b7c.JPG)
![Github3](https://user-images.githubusercontent.com/63905653/80200030-5584d480-8622-11ea-83d1-2a66568f7306.JPG)

**Comment by Gargemel** [comment]
EDIT: This version of JER seems to not do anything at all! I this version (JustEnoughResources-1.12.2-0.8.5.27) it showed ONLY VANILLA. Should I revert back to that version or is this issue just apparent in any big modpack?

**Comment by lamoyrl90** [comment]
disable stellar sky and run the command, then enable stellar sky again.

I had this same issue. I think it has to do with how JER "loads" the world being incompatible with the rendering changes introduced in Stellar Sky. Whatever it is, it worked for me just by temporarily disabling Stellar Sky.

**Comment by way2muchnoise** [comment]
JER has build in support for ores or mobs of other mods, they need to add support for JER if they want to be showed. The scan command was added to give the user the option to scan for world gen (so only ores and other blocks) as a work around.

Stellar sky indeed seems to not play nice with JER so I recommend disabling and scanning with the command. Afterwards you can re-enable and see the modded ores in JER (scanning only needs to be done once).

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore, will have to rewrite profiling for newer versions.
