### ISSUE TITLE
/jer_profile eats all of the RAM and makes Minecraft crash because of it.

### ISSUE THREAD

**Issue by Nester23** [way2muchnoise/JustEnoughResources#236]
I've been trying to do a huge chunk scan to get precise info on the blocks for my modpack, and I was met by the issue. To be exact I have 8G of RAM in my computer, so I gave it 6G of it.
So when I run </jer_profile 10000 all> command my computer is able to process around 5 dimensions before it starts to lag a lot, and then Java gets a problem with allocating memory error when Minecraft stops responding forever. I propose that you make it profile a dimension right away after it was scanned, so RAM would be as clean as possible, so even a thousand dimensions could be scanned automatically. If you can, then please make it save progress to hard drive even while dimension is being scanned, so I would be able to run something ridiculous like </jer_profile 1.000.000 all>.

**Comment by way2muchnoise** [comment]
It was never meant to do such large scans over many dimensions. It needs to be rewritten for newer version of minecraft so might have a look at improving the performance then.
