### ISSUE TITLE
how do i profile in 1.15.2

### ISSUE THREAD

**Issue by mikey34r** [way2muchnoise/JustEnoughResources#240]
im trying to see the distribution for silent gems ores but it doesnt work

**Comment by way2muchnoise** [comment]
The profiling feature has not yet been ported

**Comment by JakeMoe** [comment]
Just came to the Issues to report /jer_profile didn't seem to be a registered command; now I know why.  :-)  +1 to the request for this feature.

**Comment by STOKE-STER** [comment]
+1 for profiling feature! Using custom terrain generation like terraforged makes this a must have.

**Comment by way2muchnoise** [comment]
Closing old version issues, profiling needs to be rewritten for 1.19+ anyways
