### ISSUE TITLE
crash while profile on 1.12.2

### ISSUE THREAD

**Issue by otakup0pe** [way2muchnoise/JustEnoughResources#243]
Unlike most of the crashes I've seen already reported I'm not seeing any mod information?

```
java.lang.NullPointerException: Exception in server tick loop
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:794)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Unknown Source)
```

List of mods in our pack [here](https://github.com/tribesthatmaybe/modpack/blob/mainline/docs/mods.md). I managed to do a full profile [once](https://github.com/tribesthatmaybe/modpack/blob/mainline/src/config/jeresources/world-gen.json) but since then I've only been able to profile the overworld, when in the overworld. Any advice on troubleshooting would be lovely.

**Comment by way2muchnoise** [comment]
Could you provide a full log? Might be somewhere higher up.

You can try profiling different dimensions when you are in those dimension to track down if it is a specific one.
You can then add the ID to the blacklist in the config.

**Comment by otakup0pe** [comment]
Wild. Before I saw this response I tried from a fresh install of the same build and it's working just fine - even up to a chunk size of 1000 😕 

I'll try and reproduce and get you a full log today but if I'm unable to I will close out this machine elf of an issue.

**Comment by otakup0pe** [comment]
vOv 

i'll re-open with a crash log if i can repro

ty for the rad mod 💖
