### ISSUE TITLE
[1.16] missing chest loottables

### ISSUE THREAD

**Issue by ochotonida** [way2muchnoise/JustEnoughResources#244]
It seems you forgot to add the resource locations for ruined portals and bastion chests here, the loot doesn't show up in JEI
https://github.com/way2muchnoise/JustEnoughResources/blob/8f0228be53ff2fa2a1800163fbf1fe6015128d8b/src/main/java/jeresources/util/LootTableHelper.java#L94

**Comment by way2muchnoise** [comment]
#249 will fix this, should be merged soon
