### ISSUE TITLE
[1.16.1] Many NullPointerExceptions seemingly associated with other mods

### ISSUE THREAD

**Issue by Protected** [way2muchnoise/JustEnoughResources#250]
Example: https://gist.github.com/Protected/4364798114ce3d44150fdfe6a1fc07d4

I'm using multiplayer. These are logged on the client when JER is present. If JER isn't present, no exceptions are logged.

I don't know what are the practical in-game consequences, since I'm still setting up this server and modpack. At least some of the JER stuff works.

Forge: 32.0.106
JER: 0.11.1.93

**Comment by Protected** [comment]
Looking a bit deeper into this, it seems you're expecting net.minecraft.entity.merchant.villager.VillagerTrades.VILLAGER_DEFAULT_TRADES to have an entry for every type of villager, including types introduced by mods, which is probably not going to be true?

**Comment by way2muchnoise** [comment]
VillagerTrades.VILLAGER_DEFAULT_TRADES is populated by Forge with the trades of mods as well. I wonder whether it is already populated before JEI/JER constructs the recipes. Gonna implement a fix for the null, so at least it won't crash.
