### ISSUE TITLE
Crash with Morph in MC 1.12.2

### ISSUE THREAD

**Issue by xJon** [way2muchnoise/JustEnoughResources#251]
I'm not sure how, but a user of my modpack reported over https://github.com/xJon/The-1.12.2-Pack/issues/499 of a crash while looking up a recipe. The crash log (https://pastebin.com/7bpKsRbM) shows something is going wrong with Just Enough Resources and Morph.
Thank you!

**Comment by way2muchnoise** [comment]
Not supporting 1.12 anymore.
