### ISSUE TITLE
[1.16] Smithing Table Recipes Are Not Shown

### ISSUE THREAD

**Issue by f-raZ0R** [way2muchnoise/JustEnoughResources#256]
I'm going to be honest, I'm unsure if this is an issue with JEI, or with JER, as neither of these mods actually show smithing table recipes, despite the fact that some of these recipes **exist in vanilla**. If you try to view the recipe, of say, a netherite pickaxe, it only shows the anvil enchanting/repairing recipes, and not the diamond pickaxe+netherite ingot in a smithing table, recipe. 

This does not affect 1.16.2, as JEI added the smithing table recipes to 1.16.2, but hasn't done that to 1.16.1 yet.

**Comment by way2muchnoise** [comment]
Was added in JEI 7.3.1, see mezz/JustEnoughItems#2019
