### ISSUE TITLE
[Suggestion] Show trades for the Wandering Trader

### ISSUE THREAD

**Issue by HipHopHuman** [way2muchnoise/JustEnoughResources#259]
Showing trades for the wandering trader would be helpful, especially for Skyblock packs that use the Create mod. Create requires kelp to make its belts, and the only way to get kelp in a skyblock is via the wandering trader. Having that info in JEI would remove a lot of the guess work. I'm sure it would be helpful for other mods that add trades to the Wandering Trader, like Upgrade Aquatic

**Comment by way2muchnoise** [comment]
Support was added in #366
