### ISSUE TITLE
Jer_Profile command missing in 1.12.2?

### ISSUE THREAD

**Issue by drantral** [way2muchnoise/JustEnoughResources#260]
! I am well aware, that 1.12.2 is no longer supported !

I would like to inquire if the /jer_profile command was removed from the mod as of 1.12.2-0.9.2.60, as I am buggered to get it to function from a fresh install of the mod. JER will display Minecraft, and BOP ores with JEOI installed, but nothing else and there's no way to profile the ores in the world like so many issue logs I've hunted through have stated.

**Comment by way2muchnoise** [comment]
The command should only be missing from 1.15+
