### ISSUE TITLE
[1.16.4-forge-35.1.13] Mod kills Vanilla ore generation in modpack (Crossmod bug, Idk how to add labels)

### ISSUE THREAD

**Issue by PhoenixEvolver** [way2muchnoise/JustEnoughResources#267]
[Modpack](https://github.com/way2muchnoise/JustEnoughResources/files/5721555/Stages.of.Vanilla%2B.zip)

Almost all mods are included in this modpack with the exception of **JER**, because that seems to be the source of my issue, and **Botania**, so that I could upload the modpack zip folder (Botania is still part of the modpack).

The issue I'm currently having with this mod is that it kills all Vanilla ore generation when loaded alongside this modpack. I've tested this with the same world, using an x-ray texture. This is an issue because a number of items in the modpack require vanilla ores.

I've had this issue before with other mods, such as **Simple ores by skrallexy** conflicting with **Easy Steel by kwpugh**, and **YUNG'S Better Mineshafts by YUNGNICKYOUNG**.

[https://www.curseforge.com/minecraft/mc-mods/simpleores](url)
[https://www.curseforge.com/minecraft/mc-mods/easy-steel-forge](url)
[https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge](url)

Although it didn't hurt to much to get rid of those mods, it's a different story when I have to remove something which provides key information for obtainable, uncraftable items.

**Comment by PhoenixEvolver** [comment]
Update: Ore generation was killed without the mod, and adding it back somehow fixed it.

Idk how mods work anymore

**Comment by way2muchnoise** [comment]
So this is not a JER issue?

FYI, don't think reports can add labels only I can as far as I know :P

**Comment by PhoenixEvolver** [comment]
The issue miraculously became the problem and solution, so yeah. you can close this.
