### ISSUE TITLE
Crash when rendering mob info without GUI open

### ISSUE THREAD

**Issue by superckl** [way2muchnoise/JustEnoughResources#27]
Crash Report: http://pastebin.com/Wnsms90X
JEI Version: 2.22.4.106
JER Version: 0.2.1

The NPE comes from the assumption that there is a GUI open when determining the pitch and yaw of the mob when rendering.

https://github.com/way2muchnoise/JustEnoughResources/blob/master/src/main/java/jeresources/jei/mob/MobWrapper.java#L77

The render is done here:

https://github.com/superckl/RecipeTooltips/blob/master/src/main/java/me/superckl/recipetooltips/handler/RenderTickHandler.java#L107

A possible fix would be to have a default pitch and yaw when there is no GUI open (`mc.currentScreen == null`).

Example of when this crash would happen if it was the mob info:

http://i.imgur.com/R0SYN0P.png

**Comment by way2muchnoise** [comment]
Could you try with the latest release? I changed to the newer JEI methods that pass the mouseX, mouseY

**Comment by superckl** [comment]
Using JER 0.3.1 and JEI 2.22.4.106, I'm not seeing any recipes from JER. JER loads up fine, says it's enabled, there just aren't any recipes for items like gunpowder and rotten flesh.

**Comment by way2muchnoise** [comment]
use JEI v2.23+

**Comment by superckl** [comment]
Well, that fixes one issue, it can now display outside of a GUI properly. There's still the issue of the scissoring though...
![2016-01-28_13 06 55](https://cloud.githubusercontent.com/assets/2230216/12655758/18287d84-c5c0-11e5-8b01-04960521e5e3.png)

I would consider this issue resolved.

**Comment by way2muchnoise** [comment]
So that just leaves the scissor issue in #29
