### ISSUE TITLE
No information for Nether Gold Ore

### ISSUE THREAD

**Issue by CrafterKolyan** [way2muchnoise/JustEnoughResources#277]
There is no information for World Gen of Nether Gold Ore.

Minecraft: 1.16.5
Forge: 36.0.42
JEI: 1.16.4-7.6.1.71
JER: 1.16.4-0.12.0.104

**Comment by buttpooper23** [comment]
yes there is you are lying for atention

**Comment by CrafterKolyan** [comment]
Checked this for newer versions:
Minecraft: 1.16.5
Forge: 36.0.48
JEI: 1.16.4-7.6.1.71
JER: 1.16.4-0.12.0.109

The problem is still there. All ores work fine except for the Nether Gold Ore. Here is a proof:

https://user-images.githubusercontent.com/9883873/110749045-9fce6e80-8251-11eb-881c-4bdf47b3cfec.mp4

**Comment by way2muchnoise** [comment]
Yeah, still on the todo list to add the data

**Comment by way2muchnoise** [comment]
Nether ores were added to default compatibility layer in 189dd27172cd14956870775ba4834a9a2579185a

**Comment by CrafterKolyan** [comment]
Thank you for that @way2muchnoise. Really appreciate
