### ISSUE TITLE
Bashful mobs when rendering outside of RecipeGui

### ISSUE THREAD

**Issue by superckl** [way2muchnoise/JustEnoughResources#29]
When rendering outside of the RecipeGui, mobs do not properly render.
![2016-01-25_16 04 50](https://cloud.githubusercontent.com/assets/2230216/12567055/a5f2409a-c382-11e5-87cf-f7363b6816d0.png)

The rendering is called here:

https://github.com/superckl/RecipeTooltips/blob/master/src/main/java/me/superckl/recipetooltips/handler/RenderTickHandler.java#L229

There is a glScale followed by a glTranslate, and then draw is called. I believe the issue to be with the scissoring, but I'm not sure where the bounds would be incorrect. I have tried rendering at several z-levels to rule that possibility out.

EDIT: Definitely the glScissor:

![2016-01-27_11-24-04](https://cloud.githubusercontent.com/assets/2230216/12622280/28751c46-c4ea-11e5-9587-68d9bb9ca402.gif)

**Comment by mezz** [comment]
WTF! Reading the stack trace?
There has to be a better way.

**Comment by superckl** [comment]
In most cases, whether or not apply a ScissorHook could be determined internally by a flag you set when you call the render, no need to read the stack trace. If you wish to transform the scissor from another mod's draw call, the stacktrace method works better...

**Comment by way2muchnoise** [comment]
We'll see what it gives. It was just an idea that came to mind. I'm open for suggestions tho

**Comment by way2muchnoise** [comment]
Calling this fixed, only concerns are in #33

**Comment by superckl** [comment]
Sorry, school has had me MIA for the last few weeks. I played around with it a bit, but was having issues getting the right numbers. I just need to play with it a bit more and it should work out.

**Comment by way2muchnoise** [comment]
Well I hope you find the right numbers. If you'd need me to do anything, feel free to create a new issue. Or poke me IRC.
