### ISSUE TITLE
(ES_ES.json)

### ISSUE THREAD

**Issue by 16N1C0** [way2muchnoise/JustEnoughResources#291]
{
	"jer.config.itemsPerColumn.title": "Artículos por columna",
	"jer.config.itemsPerColumn.description": "Cambia la cantidad de elementos por columna en las vistas de mazmorra y mafia de JEI",
	"jer.config.itemsPerRow.title": "Artículos por fila",
	"jer.config.itemsPerRow.description": "Cambia la cantidad de elementos por fila en la vista de mazmorra JEI",
	"jer.config.enchantsBlacklist.title": "Lista negra de encantamientos",
	"jer.config.enchantsBlacklist.description": "Encantos de la lista negra de la vista de encantamientos JEI",
	"jer.config.diyData.title": "Usa datos de DIY en las vistas",
	"jer.config.diyData.description": "La compilación en el código de compatibilidad no se cargará y se cargarán jsons (requiere reinicio de MC)",
	"jer.config.dimensionsBlacklist.title": "Dimension Blacklist",
	"jer.config.dimensionsBlacklist.description": "Dimensiones de la lista negra del análisis de perfiles JEI",
	"jer.config.showDevData.title": "Mostrar información adicional",
	"jer.config.showDevData.description": "Principalmente para desarrolladores de paquetes. Las características incluyen pero no se limitan a promedio. bloques por plato, identificadores de entidad, ...",
	"jer.config.hiddenTabs.title": "Ocultar pestañas añadidas por JER",
	"_comment": "# no traduzca cadenas entre comillas, ya que se usan en el código",
	"jer.config.hiddenTabs.description": "Las pestañas agregadas por JER son 'mazmorra', 'encantamiento', 'mafia', 'aldeano', worldgen 'y' planta '",

	"_comment": "#Dimensiones predeterminadas",
	"jer.dim.all": "Todas",
	"jer.dim.minecraft:overworld": "Overworld",
	"jer.dim.minecraft:the_nether": "The Nether",
	"jer.dim.minecraft:the_end": "The End",

	"_comment": "#Usage: jer.page pageNumber jer.of lastPage",
	"jer.page": "Page",
	"jer.of": "of",
	"_comment": "#Usage X jer.stacks",
	"_comment": "#X will either be \"[max]\" or \"[min] - [max]\"",
	"jer.stacks": "%s Stacks",

	"jer.lightLevel": "Nivel de luz",
	"jer.any": "Ninguno",
	"jer.dim.no": "Sin dimensiones de generación válidas",
	"jer.not": "No",

	"_comment": "#Vista de mazmorra",
	"jer.dungeon.title": "Cofres de mazmorra",
	"jer.dungeon.abandonedMineshaftChest": "Pozo de mina",
	"jer.dungeon.desertPyramidChest": "Templo del desierto",
	"jer.dungeon.pyramidJungleChest": "Templo de la jungla",
	"jer.dungeon.strongholdCorridorChest": "Corredor Fortaleza",
	"jer.dungeon.strongholdLibraryChest": "Cruce de la fortaleza",
	"jer.dungeon.strongholdCrossingChest": "Cruce de la fortaleza",
	"jer.dungeon.villageBlacksmithChest": "Herrero",
	"jer.dungeon.spawnBonusChest": "Bonus",
	"jer.dungeon.simpleDungeonChest": "Calabozo",
	"jer.dungeon.netherBridgeChest": "Fortaleza del Nether",
	"jer.dungeon.endCityTreasureChest": "Ciudad del End",
	"jer.dungeon.iglooChest": "Iglú",
	"jer.dungeon.woodlandMansion": "Mansión del bosque",
	"jer.dungeon.village_weaponsmith": "Aldeano Herrero",
	"jer.dungeon.village_toolsmith": "Aldeano Herrero",
	"jer.dungeon.village_armorer": "Aldeano Herrero",
	"jer.dungeon.village_cartographer": "Aldeano Cartógrafo",
	"jer.dungeon.village_mason": "Aldeano Albañil",
	"jer.dungeon.village_shepherd": "Aldeano Pastor",
	"jer.dungeon.village_butcher": "Aldeano Carnicero",
	"jer.dungeon.village_fletcher": "Aldeano Flechero",
	"jer.dungeon.village_fisher": "Aldeano Pescador",
	"jer.dungeon.village_tannery": "Aldeano Peletero",
	"jer.dungeon.village_temple": "Templos",
	"jer.dungeon.village_desert_house": "Aldea del desierto",
	"jer.dungeon.village_plains_house": "Aldea de llanuras",
	"jer.dungeon.village_taiga_house": "Aldea de taiga",
	"jer.dungeon.village_snowy_house": "Aldea de glaciaciones",
	"jer.dungeon.village_savanna_house": "Aldea de sabana",
	"jer.dungeon.underwater_ruin_small": "Pequeña ruina submarina",
	"jer.dungeon.underwater_ruin_big": "Ruina submarina grande",
	"jer.dungeon.buried_treasure": "Tesoro enterrado",
	"jer.dungeon.shipwreck_map": "Mapa de naufragios",
	"jer.dungeon.shipwreck_supply": "Suministro de naufragios",
	"jer.dungeon.shipwreck_treasure": "Tesoro del naufragio",
	"jer.dungeon.pillager_outpost": "Puesto avanzado",
	"jer.dungeon.bastion_treasure": "Tesoro de bastión",
	"jer.dungeon.bastion_other": "Bastión otra",
	"jer.dungeon.bastion_bridge": "Puente Bastión",
	"jer.dungeon.bastion_hoglin_stable": "Bastión Hoglin estable",
	"jer.dungeon.ruined_portal": "Portal en ruinas",

	"_comment": "#Vista de encantamientos",
	"jer.enchantments.title": "Encantamientos",

	"_comment": "#Vista de planta",
	"jer.plant.title": "Artículos de plantas",

	"_comment": "#Vista del mineral",
	"jer.worldgen.title": "Generación del mundo",
	"jer.worldgen.silkTouch": "Toque de seda necesario",
	"jer.worldgen.biomes": "Spawn de biomas",
	"jer.worldgen.dimensions": "Dimensiones válidas",
	"jer.worldgen.drops": "Dropeos",
	"jer.worldgen.average": "Avg. Dropeos",
	"jer.worldgen.base": "Normal",
	"jer.worldgen.averageChunk": "Avg. bloques por chunk",

	"_comment": "#Mob View",
	"jer.mob.title": "Dropeos de Mobs",
	"jer.mob.spawn": "Bioma natal:",
	"jer.mob.biome": "Bioma natal: Pase el mouse aquí",
	"jer.mob.exp": "Experiencia que dropea",

	"_comment": "#Ver comercios",
	"jer.villager.title": "Comercios",

	"_comment": "#Conditionals - when translating retain '%s' as this lets the modifier be properly inserted into the string\"jer.magmaCream.text\": \"Small and Large Magma Cubes\",",
	"jer.slimeBall.text": "Solo slimes diminutos",
	"jer.rareDrop.text": "Dropeos raros",

	"jer.slimeScale.text": "Escalas con tamaño de slime",
	"jer.kingSlime.text": "Solo el rey slime",
	"jer.beheading.text": "La decapitación aumenta las posibilidades",
	"jer.randomAspect.text": "Aspecto aleatorio",
	"jer.equipmentDrop.text": "Dropeos de equipamiento",
	"jer.affectedByLooting.text": "Afectado por el saqueo",
	"jer.powered.text": "Cuando es potenciado",
	"jer.burning.text": "Cuando está en llamas",
	"jer.notBurning.text": "Cuando no está en llamas",
	"jer.wet.text": "Cuando está mojado",
	"jer.notWet.text": "Cuando no está mojado",
	"jer.hasPotion.text": "Cuando se ve afectado por %s",
	"jer.hasNoPotion.text": "Cuando no se ve afectado por %s",
	"jer.beyond.text": "Más que %sm para spawnear",
	"jer.nearer.text": "Más cerca que %sm para spawnear",
	"jer.raining.text": "Cuando llueve",
	"jer.dry.text": "Cuando no llueve",
	"jer.thundering.text": "Cuando hay asalto",
	"jer.notThundering.text": "Cuando no hay asalto",
	"jer.moonPhase.text": "Durante %s Luna",
	"jer.notMoonPhase.text": "Fuera de %s Luna",
	"jer.pastTime.text": "Día pasado %s",
	"jer.beforeTime.text": "Día antes %s",
	"jer.pastWorldTime.text": "Mundo pasado %s",
	"jer.beforeWorldTime.text": "Mundo de antes %s",
	"jer.pastWorldDifficulty.text": "Dificultad del mundo de antes %s",
	"jer.beforeWorldDifficulty.text": "Antes de la dificultad del mundo %s",
	"jer.gameDifficulty.text": "Dificultad %s",
	"jer.notGameDifficulty.text": "Sin dificultad %s",
	"jer.inDimension.text": "En la dimensión %s",
	"jer.notInDimension.text": "No en la dimensión %s",
	"jer.inBiome.text": "En el bioma %s",
	"jer.notInBiome.text": "No en el bioma %s",
	"jer.onBlock.text": "Encendido %s",
	"jer.notOnBlock.text": "Apagado %s",
	"jer.below.text": "Abajdo del nivel %s",
	"jer.above.text": "Encima del nivel %s",
	"jer.playerOnline.text": "Cuando el jugador %s está online",
	"jer.playerOffline.text": "Cuando el jugador %s está offline",
	"jer.playerKill.text": "Asesinado por un jugador",
	"jer.notPlayerKill.text": "Asesinado por ningún jugador",
	"jer.aboveLooting.text": "Encima de Saqueo %s",
	"jer.belowLooting.text": "Abajo de Saqueo %s",
	"jer.killedBy.text": "Cuando es asesinado por%s",
	"jer.notKilledBy.text": "Cuando no es asesinado por %s",

	"_comment": "#Moon Phases",
	"jer.full.moon": "Completa",
	"jer.waning_gibbous.moon": "Gibosa menguante",
	"jer.third_quarter.moon": "Tercer cuarto",
	"jer.waning_crescent.moon": "Creciente menguante",
	"jer.new.moon": "Nueva",
	"jer.waxing_crescent.moon": "Luna creciente",
	"jer.first_quarter.moon": "Primer cuarto",
	"jer.waxing_gibbous.moon": "Luna menguante"
}

**Comment by way2muchnoise** [comment]
Would be a lot easier to pull into the project if you made a Pull Request instead of an issue.

**Comment by way2muchnoise** [comment]
Implemented in #302
