### ISSUE TITLE
Mobs don't look directly at the mouse

### ISSUE THREAD

**Issue by mezz** [way2muchnoise/JustEnoughResources#3]
![2016-01-10_10 14 26](https://cloud.githubusercontent.com/assets/916092/12223125/a6a9c522-b783-11e5-8e3e-52bfd5847fe3.png)

My cursor is right in the center of the zombie's face, it should be looking forward like the player character does.

**Comment by way2muchnoise** [comment]
Improved in 054ebc53f6b83982875b5221e90f632f1c8aa0db
