### ISSUE TITLE
Incompatibility with Untamed Wilds

### ISSUE THREAD

**Issue by AnasterianSunstrider** [way2muchnoise/JustEnoughResources#303]
This is probably an issue on the other side but just to be sure, I'll post it here too since im not an expert on how mods work.  The mob drops don't show up when i have both mods installed. If you have some spare time please look into this issue.

**Comment by way2muchnoise** [comment]
What drops are not automatically added to JER, the mod needs to add support. Automatic discovery was nearly impossible in earlier version of MC, but seems more feasible now so that might get added in the future (if I find some time).
