### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by Reithsaw** [way2muchnoise/JustEnoughResources#306]
Hi, i wan't to use the profiling but when i used the command " /jer_profile 100 true " i have a message " Command not implemeted " (And yes you wrote " implemeted ") 

I used the latest version (JustEnoughResources-1.16.5-0.12.1.127 and jei-1.16.5-7.7.1.118)

**Comment by Diversion98** [comment]
I have the same issue with the same version of JER

**Comment by way2muchnoise** [comment]
Still need to work on getting that re-implemented with all the changes in the newer versions of MC. I'll update the message to be a bit clearer that it will be back in future versions.
