### ISSUE TITLE
1.12.2 Guide Request

### ISSUE THREAD

**Issue by tyon2006** [way2muchnoise/JustEnoughResources#309]
Hello! I'm a 1.12.2 pack maker. I'd like to understand how to get modded/custom mob drops and loot tables to appear in JER's lists. I see primitive mobs showing up in the mob drops, but no other modded drops (200+ mods with over 500 unique mobs, each with a custom drop). Any how to's or hints on this would be greatly appreciated.

**Comment by way2muchnoise** [comment]
I never got around to implementing a way for pack authors to add drops. Idea in newer versions was to use the data in the newer loot tables (also still to be implemented).

Your best shot would be to use the API, which does involve adding your own mod.
The interface for that can be found [here](https://github.com/way2muchnoise/JustEnoughResources/blob/1.12.2/src/main/java/jeresources/api/IMobRegistry.java)
