### ISSUE TITLE
[1.17] Missing vanilla ores

### ISSUE THREAD

**Issue by Da-Technomancer** [way2muchnoise/JustEnoughResources#313]
In the MC1.17+ version, there's no world gen recipe/generation graph for vanilla deepslate ores or copper ore.

**Comment by vedrit** [comment]
I don't see any world gen graphs for any ores. Profiling doesn't exist in 1.17+ and I don't know how to supply the mod with a world-gen.json and there's no JER config folder

**Comment by way2muchnoise** [comment]
Added 1.18 ore gen, don't really care too much about deepslate as it is just a sub-zero variant of ores. Might add it is QoL stuff later.
