### ISSUE TITLE
[1.18.1] Hidden tabs help.

### ISSUE THREAD

**Issue by KKotik** [way2muchnoise/JustEnoughResources#323]
What values can go in this config option?

**Comment by way2muchnoise** [comment]
mob, dungeon, worldgen, plant, enchantment, villager

See https://github.com/way2muchnoise/JustEnoughResources/blob/master/src/main/java/jeresources/jei/JEIConfig.java#L35-L40

**Comment by KKotik** [comment]
Thank you!
