### ISSUE TITLE
The Latest Update is Causing World Loading Freeze

### ISSUE THREAD

**Issue by Camawama** [way2muchnoise/JustEnoughResources#326]
[2022-01-30-5.log](https://github.com/way2muchnoise/JustEnoughResources/files/7967280/2022-01-30-5.log)

It took me a bit to find the culprit mod, but JER is causing worlds to not load on my modpack after the latest update.

**Comment by egguchan** [comment]
Hi, i'm having the same problem. Your log looks incomplete, the error message we get in Issue #325 appears just below the last line in your log, so I suspect it's the same issue. We have to wait around 10 minutes for a small single-player world to load.

**Comment by Pentasis** [comment]
Same here. Loading hangs on dirt-screen. Removing JER resolves this.

**Comment by Wedge1453** [comment]
tried on forge 39.0.54, 39.0.63, and 39.0.64, same issue

**Comment by Jessman5** [comment]
+1 on this
Console is stuck at this line 
` [Render thread/INFO] Registering categories: minecraft:jeresources ...`
while on the dirt screen to join the selected world. 
Occurred after installing latest version 1.18.1-0.13.1.148 but the issue is still there after downgrading back to 147. 

Fixed after downgrading back to 141 version.

**Comment by thebulletprooftiger** [comment]
game freezes and crashes on world load. broke modpack. took awhile to find JER as the culprit xD

**Comment by way2muchnoise** [comment]
@mezz I though you improved stuff with #322 😆

**Comment by way2muchnoise** [comment]
Currently being build and should be up on CF soon. Please validate and close if it works again :)

**Comment by Camawama** [comment]
Awesome, I will check this rn. Thank you!

**Comment by way2muchnoise** [comment]
Closing as there seem to be no further reports on this issue
