### ISSUE TITLE
Newest 1.18 update returns an Exit Cote 1 on startup

### ISSUE THREAD

**Issue by WordStormRose** [way2muchnoise/JustEnoughResources#330]
Good day,

I am using JER in my modpack which I am slowly updating from 1.16 to 1.18 and the newest update (0.14.0.154) of JER for 1.18 gives me the error message screenshotted below when trying to start my game. Returning to the previous update (0.13.2.153) allows minecraft to boot as normal.
![image](https://user-images.githubusercontent.com/54124339/155861807-b110ed69-3930-4784-ba04-1c1da8750225.png)

**Comment by way2muchnoise** [comment]
Could you please provide a client log?

**Comment by WordStormRose** [comment]
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/8163864/latest.log)
I was watching the log as it went though and it noted a missing JEI, but JEI is fully updated as far as I can see.

**Comment by WordStormRose** [comment]
Update: I just double-checked JEI in the curseforge app and seems like it hadn't done the usual appears-at-the-top-of-the-list thing to notify for an update; I've done so and all is well now

**Comment by way2muchnoise** [comment]
So we can close this?

**Comment by WordStormRose** [comment]
Yes
