### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null Crash

### ISSUE THREAD

**Issue by Dweebul** [way2muchnoise/JustEnoughResources#332]
Can't even get to title screen before it crashes
[latest.log](https://github.com/way2muchnoise/JustEnoughResources/files/8191184/latest.log)

**Comment by way2muchnoise** [comment]
You need to update JEI to version 9.4 or above when using JER 0.14+

**Comment by Dweebul** [comment]
> You need to update JEI to version 9.4 or above when using JER 0.14+
It was updated to JEI 9.4+ when I submit this. I even uninstalled and reinstalled both and I still get the same crash.

**Comment by Dweebul** [comment]
If it means anything, I also have [Just Enough Professions](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep) installed as well as [JEITweaker](https://www.curseforge.com/minecraft/mc-mods/jeitweaker).
