### ISSUE TITLE
[1.18.2] Thermal Series ores don't show up in JEI/JER

### ISSUE THREAD

**Issue by Peca21** [way2muchnoise/JustEnoughResources#343]
I just added thermal mods to my modpack, created a new world and the ores are spawning fine but are not visible in JEI world gen tab.
Forge 40.1.25
1.18.2
JustEnoughResources-1.18.2-0.14.1.167
JER-Integration-3.3.1
jei-1.18.2-9.7.0.195
EDIT: Here is the log from a modpack that has only JEI JER JER Integration and thermal
https://paste.ee/p/c1HWY

**Comment by way2muchnoise** [comment]
Not really a JER issue, the information for mods is added by JER-integration.  
Paging @AlasDiablo from [JER-Integration](https://github.com/Janoeo/JER-Integration)
