### ISSUE TITLE
[1.18.2] JER not working at all, exception thrown in log during world loading

### ISSUE THREAD

**Issue by minghinshi** [way2muchnoise/JustEnoughResources#347]
I have an instance in MultiMC in 1.18.2 (Forge version: 40.1.51) with only JEI (9.5.5.174) and JER (0.13.1.141) installed. I loaded up a world and click on things like coal ore and wheat for the JER recipes, but nothing from JER shows up at all. JEI still works.

Looking at the log, it seems like a `java.lang.NoClassDefFoundError` is thrown while the world is being loaded, which could have stopped JER from loading. 

https://paste.ee/p/m94ew

**Comment by way2muchnoise** [comment]
Might want to try a JER version that is actually for 1.18.2 ([link to 1.18.2 version on CF](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/all?filter-status=1&filter-game-version=2020709689%3A9008))

**Comment by minghinshi** [comment]
Thanks, I knew I must have overlooked something. Sorry for the inconvenience.
