### ISSUE TITLE
[1.19] Update with API changes

### ISSUE THREAD

**Issue by QuentiumYT** [way2muchnoise/JustEnoughResources#348]
Hello, I'm looking for a new version of this mod in 1.19

I've looked at it and there is a few changes in BiomeRestriction with name changes, TextComponent is now Component and few other things.
I'm not a Java developer, just curious if I can help with that but it starts getting out of my competences.

Hope to see it soon :) thanks

**Comment by way2muchnoise** [comment]
Feel free to PR if you want to contribute, will make the project run on both Fabric and Forge first for 1.18 and then port it over to 1.19. This will take me some time as this is just a hobby and free time is scarce these days.
