### ISSUE TITLE
JER Not showing blocks from modded Dimensions in World Gen tabs.

### ISSUE THREAD

**Issue by MdBourg98** [way2muchnoise/JustEnoughResources#352]
JER Not showing blocks from modded Dimensions in World Gen tabs. Also not showing blocks that I KNOW generate in the overworld, Like DeepSlate diamond/DS emeralds/DS gold/DS redstone ores. World-Gen.json is in config folder, but its like it only sees part of it.

**Comment by way2muchnoise** [comment]
Mods have to add their own support to show their ores in the World Gen tab. User workaround used to the profiling but that remains to be re-implemented.

Added deepslate stuff in 0f66af1acf16ddde05521405b70374a393280387, will be in version 1.1.1.
