### ISSUE TITLE
Does not appear in JEI

### ISSUE THREAD

**Issue by SharkBaitRFSR** [way2muchnoise/JustEnoughResources#357]
I made a small modpack revolving mainly around mekanism and JER does not appear in JEI. I thought it may have been due to a missing update with jei but upon updating it still did not appear.
1.19.2 forge

**Comment by LorenzoCardinali** [comment]
same problem here, running forge 43.1.2 (also tried 42.1.1)

**Comment by way2muchnoise** [comment]
What version of JER are you using?

**Comment by SharkBairRFSR** [comment]
I don't know the number of the top of my head but it's the most recent on the curse forge launcher.

**Comment by way2muchnoise** [comment]
Can you try with the new beta? Version 1.19.2-1.1.0.178

**Comment by SharkBairRFSR** [comment]
I will check it out when I get home and update you

**Comment by zISKo666** [comment]
Hey there,
It never worked for me with 1.19.x
I've tried the latest version of Forge, JEI and JER w/o any other mod installed.

Here is my latest.log
https://paste.ee/p/ZZdaD

**Comment by SharkBairRFSR** [comment]
The beta one did not work either

**Comment by SharkBairRFSR** [comment]
Why was this closed the issue was not resolved?

**Comment by way2muchnoise** [comment]
The version with the fix is just uploaded waiting for CF to release it.
https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/3951643

**Comment by SharkBairRFSR** [comment]
Alrighty I'll check when I get home

**Comment by way2muchnoise** [comment]
Version is online: 1.1.0.179. Feel free to reopen if it doesn't work.

**Comment by LorenzoCardinali** [comment]
Works with Forge 43.1.3
