### ISSUE TITLE
[1.12.2] Polar Bears not registered in LootTableHelper

### ISSUE THREAD

**Issue by unnecessary1234** [way2muchnoise/JustEnoughResources#388]
Minecraft: 1.12.2
JER: 1.12.2-0.9.2.60
Forge: 14.23.5.2859

Polar Bears are not registered in 1.12.2. Rather amusingly, after seven years gone unnoticed I discovered this due to a personal Modpack I am building; it requires a way to get fish without water. I am willing to test and submit a pull request if needed. I understand if it is impractical to update the branch after all this time and am comfortable using a mod to patch this using the API. Thank you for any communication.

**Comment by way2muchnoise** [comment]
Willing to merge and release if you want create a PR to the 1.12.2. The version is not support anymore (by me), but happy to release a new version if you create a PR.

**Comment by unnecessary1234** [comment]
Alright, thanks. I need a bit to figure out Git and set up a 1.12.2 dev enviroment. I should be done by around noon tomorrow.

**Comment by unnecessary1234** [comment]
Fixed by #391
