### ISSUE TITLE
More logic needed to exactly match mob on adding drops

### ISSUE THREAD

**Issue by P3pp3rF1y** [way2muchnoise/JustEnoughResources#41]
I have submitted PR that fixes an issue where it was impossible to add drops to preexisting mobs #40.
But to exactly match zombie and skellies (and possibly even more if mod devs extend vanilla entitites) you will want to add logic similar to NER (method below).

Wasn't sure where exactly you would want to put this. My thought given that probably I am the first one using addDrops is to add the logic in MobRegistry.addDrops and have mod devs pass in entity instance from which you can read everything you need. On the other hand I feel that in this class you would want to always exact match so perhaps the only additional bit of info needed is for wither skelly. (but I may be missing something regarding the exact match)

    public Set<MobEntry> getRegistryMatches(Class clazz, boolean exactMatch, boolean witherSkeleton)
    {
        Set<MobEntry> result = new LinkedHashSet<MobEntry>();
        int wither = witherSkeleton ? 1 : 0;
        for (MobEntry regEntry : registry)
        {
            Set classes = new LinkedHashSet();
            if (exactMatch) classes.add(regEntry.getEntity().getClass());
            else classes = ClassScraper.getGeneralizations(regEntry.getEntity().getClass());
            for (Object generalClass : classes)
            {
                if (generalClass == clazz)
                {
                    if (exactMatch && clazz == EntitySkeleton.class)
                        if (((EntitySkeleton) regEntry.getEntity()).getSkeletonType() != wither) break;
                    result.add(regEntry);
                }
            }
        }
        return result;
    }

**Comment by way2muchnoise** [comment]
@P3pp3rF1y You think this will do?

**Comment by P3pp3rF1y** [comment]
Looks good to me. Definitely works for my needs. 

But you may want to add a bit more for when mod devs need to match to exact entity that is a parent entity to another one - like if you need to add drops to Zombie but not to Zombie Pigman or Spider but not cave spider. At least I don't see these defined in DataWatcher. (But it's very well I am blind looking in there or in your code changes :D)

**Comment by way2muchnoise** [comment]
That should be all then I'll hit you up when I release a version with it.

**Comment by P3pp3rF1y** [comment]
Thanks, I actually just had a moment of an oops where I spent half an hour debugging why my drops are not showing up in JER, followed by a good laugh when I debugged right to the line that I have PRed, but that obviously wasn't changed in my test. :D

**Comment by P3pp3rF1y** [comment]
After trying to implement addDrops with WatchableData the logic fails on line 126 in WatchableData. The type of object.getObject() is byte and obj is integer so equals returns false even for the "same" values. 

doing inSet = object.getObject().equals(((Integer) obj).byteValue()) instead works. 

But it's late for me so I am not going to make the change and PR it today. May do it tomorrow.
