### ISSUE TITLE
Not showing ores from other mods

### ISSUE THREAD

**Issue by Aceplante2** [way2muchnoise/JustEnoughResources#430]
title. forge 1.18.2

**Comment by way2muchnoise** [comment]
This is intended behaviour, by default only default ores are supported. Other mods can register their ores through the API, or you can use the DYI ore feature. Sadly I don't really have time to re-implement the scanning feature however there is: [RundownRhino/RegionScanner](https://github.com/RundownRhino/RegionScanner) which allows you to generate the json that is used for doing DYI graphs.
