### ISSUE TITLE
Adding Mod Compatibility

### ISSUE THREAD

**Issue by LiteWolf101** [way2muchnoise/JustEnoughResources#431]
Hello!

How would I go about adding compatibility to my mod so that my mod's loot tables show up on JER?

Thank you!

**Comment by way2muchnoise** [comment]
Hey, you can use the [API](https://github.com/way2muchnoise/JustEnoughResources/tree/master/CommonApi/src/main/java/jeresources/api )specifically the [MobRegistry](https://github.com/way2muchnoise/JustEnoughResources/blob/master/CommonApi/src/main/java/jeresources/api/IMobRegistry.java) to register your own mods mobs.

You mainly need to start from creating a class that implements [IJERAPI](https://github.com/way2muchnoise/JustEnoughResources/blob/master/CommonApi/src/main/java/jeresources/api/IJERAPI.java). Forge needs an annotation, Fabric works with an entry point. From there you can access the MobRegistry to register your mobs.

Hope this helps!
