### ISSUE TITLE
backport villager tab texture fix to 1.20.1

### ISSUE THREAD

**Issue by MacChuck** [way2muchnoise/JustEnoughResources#440]
Villagers have no texture when viewed in the villager tab, in the version of JER for forge 1.20.1.
Referencing this issue: https://github.com/way2muchnoise/JustEnoughResources/issues/418

The fix was made in 1.20.2, please backport this fix to 1.20.1. With forge & neoforge diverging at 1.20.2, and waiting on other mods, there's potential update issues.

**Comment by way2muchnoise** [comment]
Backported in a2dff207ef1e9158c396d770644636aacbf28c5d
