### ISSUE TITLE
Registering villager / at cartographer 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [way2muchnoise/JustEnoughResources#454]
JustEnoughResources-1.19.2-1.2.3.243.jar

[Render thread/WARN] [jeresources/]: Failed loading villager cartographer registered at cartographer
[Log.txt](https://github.com/way2muchnoise/JustEnoughResources/files/14200560/Log.txt)

**Comment by katubug** [comment]
Same issue in 1.20.1: https://legacy.curseforge.com/minecraft/mc-mods/supplementaries/issues/952

It happens with multiple villager types, as well.

**Comment by Krimatoria** [comment]
It crashes with an error, but I do not know if this is related or not. The warning is the last one in the log after departure.
![image](https://github.com/way2muchnoise/JustEnoughResources/assets/106809386/5fedb438-0549-4716-a422-541ecada66ca)
[Log 7.txt](https://github.com/way2muchnoise/JustEnoughResources/files/14319384/Log.7.txt)
![image](https://github.com/way2muchnoise/JustEnoughResources/assets/106809386/65c8d342-ac88-48c3-bdcc-b671a8c598c4)
