### ISSUE TITLE
Fabric and Forge 1.20.4

### ISSUE THREAD

**Issue by wolfieboy09** [way2muchnoise/JustEnoughResources#463]
JER Is super helpful, and the latest version is `1.20.1`. The server I play on is `1.20.4`, and I miss JER on `1.20.4``

**Comment by way2muchnoise** [comment]
1.20.4 is available as alpha build

https://modrinth.com/mod/just-enough-resources-jer/versions?g=1.20.4

https://legacy.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/all?filter-status=1&filter-game-version=2020709689%3A10407
