### ISSUE TITLE
1.19.2 Need help blacklisting an entity so it doesn’t appear in mob drops.

### ISSUE THREAD

**Issue by NoalSimon** [way2muchnoise/JustEnoughResources#484]
Need to blacklist two aether redux entities from appearing in mob drops as attempting to render them causes a crash. the blightbunny spawner and cockatrice spawner both cause the crash.

**Comment by NoalSimon** [comment]
because the aether redux specifies that the entity shouldn't be rendered and jer is attempting to force it to render, it causes the issue and crashes

**Comment by way2muchnoise** [comment]
Currently there is no mob blacklisting feature in JER. Could you share a log file and screenshots of the issues/crash?

**Comment by NoalSimon** [comment]
The dev for aether redux already fixed the issue on their end. on a previous version before 2.0.16c for aether redux, it would attempt to render an entity without a valid thing to render so it would crash. gimmie a moment to recreate the crash

**Comment by NoalSimon** [comment]
[crash-2024-06-16_19.47.25-client.txt](https://github.com/user-attachments/files/15860182/crash-2024-06-16_19.47.25-client.txt)

**Comment by way2muchnoise** [comment]
Closing this issue considering this was fixed on Aether Redux side, and I'm not actively supporting 1.19.2 anymore
