### ISSUE TITLE
Port to 1.9

### ISSUE THREAD

**Issue by way2muchnoise** [way2muchnoise/JustEnoughResources#49]
Once the lazy @mezz moves his ass :D

**Comment by mezz** [comment]
I'm working on it currently. Couldn't do it before since block and item colors were all derped.

**Comment by mezz** [comment]
Knock yourself out :)
https://github.com/mezz/JustEnoughItems/tree/1.9

**Comment by way2muchnoise** [comment]
@mezz [official 1.9 builds](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.html)

**Comment by way2muchnoise** [comment]
I seems the profiling works but it isn't shutdown the profiling mode correctly so it crashes the game.
If you could have a look at it @mezz since I have no clue what you are doing in `DummyWorld`

**Comment by mezz** [comment]
I'll take a look later today. `DummyWorld`'s goal is to stop lighting calculations, entity spawning, and saving the chunks.

**Comment by way2muchnoise** [comment]
Well this is done
