### ISSUE TITLE
do you have a plan to release to 1.21.1 neoforge

### ISSUE THREAD

**Issue by Darwin-Gabriel** [way2muchnoise/JustEnoughResources#520]
do you have any eta

**Comment by kierohere** [comment]
I forked and updated the mod to version 1.21.1. Here: https://github.com/kierohere/JustEnoughResources/releases/tag/release

**Comment by way2muchnoise** [comment]
Yes, I will release a version once I figure out the issue with https://github.com/way2muchnoise/JustEnoughResources/issues/514#issuecomment-2440120162

**Comment by FaNt4zMa** [comment]
Are you still working on 1.21 Neo? Thanks
