### ISSUE TITLE
Forked and updated to 1.21.1

### ISSUE THREAD

**Issue by kierohere** [way2muchnoise/JustEnoughResources#522]
If the creator updates their mod to version 1.21.1, I will remove mine. For now, you can use the one provided in the link:

https://github.com/kierohere/JustEnoughResources/releases/tag/release

**Comment by manmaed** [comment]
#514 happens on your fork

**Comment by way2muchnoise** [comment]
The mod builds just fine for 1.21 on Forge/NeoForge but has a runtime ClassNotFound issue.
