### ISSUE TITLE
How do i blacklist or fix this incompatibility between JER and Immersive Interfaces

### ISSUE THREAD

**Issue by DeadGator** [way2muchnoise/JustEnoughResources#525]
Don't want to remove the resource pack but neither the mod, maybe i can blacklist the villager trades tab? I tried messing around with the blacklist tab but idk how to format it to blacklist the villager trades.

![2024-12-06_21 50 17](https://github.com/user-attachments/assets/701449e6-efbb-44ec-a0ff-400df15254c5)
![2024-12-06_21 49 35](https://github.com/user-attachments/assets/42c7a97e-f931-46a8-972f-07c2daa6f4bf)

**Comment by way2muchnoise** [comment]
In the config you can hide the Villager trades by adding `villager` to `hiddenTabs`.
