### ISSUE TITLE
JEI failing to start

### ISSUE THREAD

**Issue by ryanjo1982** [way2muchnoise/JustEnoughResources#54]
Looks like JER is causing JEI to not start. I am going to post this on both Git's as I cannot tell which mod caused the error. It causes the client to crash.

http://paste.ee/p/mPaN9

**Comment by way2muchnoise** [comment]
I update for the latest forge already you can get it from [the build server](https://drone.io/github.com/way2muchnoise/JustEnoughResources/files)

**Comment by ryanjo1982** [comment]
Thank! I will grab that tonight and let you know what happens.

**Comment by way2muchnoise** [comment]
I just published the builds for new versions of forge to Curse aswell

**Comment by way2muchnoise** [comment]
@ryanjo1982 is this issue fixed?

**Comment by ryanjo1982** [comment]
@way2muchnoise yes. It is fixed.
