### ISSUE TITLE
Profile command doesn't work.

### ISSUE THREAD

**Issue by majix560** [way2muchnoise/JustEnoughResources#56]
I've used "/profile 100 all", "/profile 3 all", and "/profile 9 all".
Every time I try to use the command absolutely nothing happens at all in the game.
While I get this pastebin in the console.
http://pastebin.com/5i2DEttm

Here is the list of mods I have.
http://pastebin.com/UrSA5cXN

**Comment by way2muchnoise** [comment]
How is your instance even working? You have a 1.9 Forge version and a bunch of 1.8.9 mods. Also try the latest JER (either from [the build server](https://drone.io/github.com/way2muchnoise/JustEnoughResources/files) or [CurseForge](http://minecraft.curseforge.com/projects/just-enough-resources-jer)) (gonna guess your forge version in your list might be wrong)

Does it crash without the `all` as well?

**Comment by majix560** [comment]
Oops, provided the mod list for the wrong pack version.
Original post will be updated with correct mod list.

**Comment by majix560** [comment]
I goofed up on writing the pack xml.

**Comment by majix560** [comment]
It's actually 1.8.9 forge, but I forgot to update the entry in the mods list.

**Comment by majix560** [comment]
I already have the latest version of it for 1.8.9 from CurseForge
Which "Master" build on the build server is for 1.8.9?
The "1.8.9" build failed.

P.S. It's actually 1.8.9 forge, but I forgot to update the entry in the mods list.
Other then the "1.9" it lists the correct 1.8.9 forge used.

**Comment by way2muchnoise** [comment]
yeah the failed build has nothing to do with your issue, but I'll see what is going wrong. Can you test it without the `all` param?

**Comment by way2muchnoise** [comment]
Once the [new version](http://minecraft.curseforge.com/projects/just-enough-resources-jer/files/2297020) is up on CF could you try it out?

**Comment by majix560** [comment]
Tried "/profile 3" on 0.4.0-final.
Now it actually crashes unlike the original 0.4.0
http://pastebin.com/pWxZsrFP

**Comment by way2muchnoise** [comment]
Hmm, could you try without the malisis core mods? If you have the time, try and remove some mods and see what happens.

**Comment by majix560** [comment]
Removed the mods by malisis.
It's working now

**Comment by way2muchnoise** [comment]
K, I'm going to call this issue closed. But if you could make a new one about the malisis issues and one on their repo (if they have one?) and link it.
