### ISSUE TITLE
Doesn't load anything when json file is present.

### ISSUE THREAD

**Issue by majix560** [way2muchnoise/JustEnoughResources#57]
It doesn't load anything when the json file is present.
When in diy mode doesn't load the json file and thus shows nothing.
Even when diy = false and using the compat build, it won't load anything (and show nothing) if the world-gen-scan.json file is present.
Here is the entire console log from the ATLauncher.
http://pastebin.com/q26ePceV
Start reading on line 494

**Comment by majix560** [comment]
Actually I just tried it without the json, and it still doesn't work.

**Comment by mezz** [comment]
The json file must be renamed to `world-gen.json`. This is to prevent scanning from overwriting an existing world-gen file. I just find it confusing, yell at @way2muchnoise :D

**Comment by way2muchnoise** [comment]
Seems like I never added the obf name in the 1.8.9 version. Added it in 28ae9087c8b815c0932719a8a9ad372afcdb26a4. New version up on CF soon.

**Comment by way2muchnoise** [comment]
@majix560 Can you try the new release on CF?

**Comment by majix560** [comment]
still doesn't load it, but the crashing on /profile is back.
http://pastebin.com/6CS06w4R

**Comment by way2muchnoise** [comment]
It doesn't load what?

**Comment by way2muchnoise** [comment]
As I can see in the logs you aren't using either the recommended or latest version of forge. You might want to go latest here as both JEI and JER are build against it

**Comment by KovuTheHusky** [comment]
I think I'm getting the same thing with Forge #1877, JEI 3.3.3.197 and JER 0.4.5.24. It loads fine, appears in the mod options list, but doesn't appear to actually do anything. Almost as if JEI isn't detecting/using it. Not sure how JEI addons work so I don't know what else to say.

**Comment by way2muchnoise** [comment]
@KovuTheHusky Could you post your client log? That way I can see what goes wrong

**Comment by KovuTheHusky** [comment]
I would have done so initially but nothing seems out of the ordinary.

https://gist.github.com/KovuTheHusky/0b56cff6919b5f72cac4cfc96005ae95

**Comment by way2muchnoise** [comment]
@KovuTheHusky Well that is cause you didn't load a world. JEI (and thus JER) gets loaded when a world is loaded. So you might want to post a log where a world is joined

**Comment by KovuTheHusky** [comment]
Before I go any further, does JER require JER be installed on the server or that the server is a Forge (and not Vanilla/CB) server?

**Comment by KovuTheHusky** [comment]
Well it worked in a newly created singleplayer world and I immediately tried it on a multiplayer world. Worked fine. Restarted the game, doesn't work on anything anymore. Race condition maybe? Here's a log from one of my unsuccessful attempts.

https://gist.github.com/KovuTheHusky/2c95487e96fd2a7c7cca71cedc14db36

**Comment by way2muchnoise** [comment]
@KovuTheHusky The log you provided doesn't even say anything about JER nor JEI. It starts to fail in the default thread execution code from minecraft. I have no clue what is going wrong here.

**Comment by KovuTheHusky** [comment]
What version of Forge do you test on currently?

**Comment by KovuTheHusky** [comment]
After some testing, JER will work fine if the very first thing I do it load a singleplayer world. If I load a multiplayer world first, JER will not work. If I restart the game and load a singleplayer world (and then any single/multiplayer world after) it works fine.

**Comment by mezz** [comment]
Confirmed, it's not working when connecting to a server.

**Comment by way2muchnoise** [comment]
@KovuTheHusky @mezz Does the [new build](http://minecraft.curseforge.com/projects/just-enough-resources-jer/files/2298017) solve the issue?

@majix560 Does it solve your issue as well? If not could you make a new issue for it with a more detailed description.

**Comment by KovuTheHusky** [comment]
Perfect! Thank you so much. Works fine now. If I knew more about FML I would have dug deeper and made a PR. Thanks for your quick work. Glad my stacktrace helped at least.

Thanks again!

**Comment by way2muchnoise** [comment]
@KovuTheHusky It is kind of a dirty fix cause it won't load server edited loot tables. But that would require me to write a whole ton of code for the server side to sent them over. And I don't feel like writing that atm. Maybe I will one day or maybe Forge will add some goodies for it. Who knows.
