### ISSUE TITLE
JER 1.9-0.4.5.24 crashes client while cycling items in JEI

### ISSUE THREAD

**Issue by kreezxil** [way2muchnoise/JustEnoughResources#61]
crash report: http://pastebin.com/V5ahFYh2

**Comment by boomshroom** [comment]
I have the same crash. From what I can tell, it's checking both inputs to a villager trade and it seems that 1 is empty.

**Comment by way2muchnoise** [comment]
Should with #62, try the new build up on curse soon

**Comment by way2muchnoise** [comment]
@kreezxil @boomshroom can any of you confirm that this issue is fixed?
