### ISSUE TITLE
JER is simply not showing up.

### ISSUE THREAD

**Issue by ExperimentCode3** [way2muchnoise/JustEnoughResources#63]
I do not experience a crash or anything like that, but JER simply does not show any oregen, mob drops, or dungeon loot. I can't find any evidence of it existing even though it is installed and shows up in the mods tab in game. I have the latest versions of JEI and JER. Am I doing something wrong or is this a bug?

**Comment by way2muchnoise** [comment]
Could you post a client log? That way I can find what is going wrong

**Comment by ExperimentCode3** [comment]
Here is the log (I think) from my most recent run

[2016-05-17-5.log.gz](https://github.com/way2muchnoise/JustEnoughResources/files/268982/2016-05-17-5.log.gz)

**Comment by way2muchnoise** [comment]
This is a log but not the full one as it has no info about the loading of JEI even.

**Comment by ExperimentCode3** [comment]
I think this is the right one then. Sorry about this, First time reporting a bug.

[fml-client-latest.txt](https://github.com/way2muchnoise/JustEnoughResources/files/268987/fml-client-latest.txt)

**Comment by way2muchnoise** [comment]
Could you try the [latest alpha up on CF](http://minecraft.curseforge.com/projects/just-enough-resources-jer)

**Comment by ExperimentCode3** [comment]
it works! However, under mob drops i noticed that zombies are not noted as dropping potatoes and iron ingots as I believe they do . Just wanted to mention i noticed it in case it could cause trouble in the future. Thank you very much!

**Comment by way2muchnoise** [comment]
I'll look into that. Maybe make a new issue for that with a screenshot.
