### ISSUE TITLE
[1.9.4] - Possible "Mod Config" Support

### ISSUE THREAD

**Issue by Lanse505** [way2muchnoise/JustEnoughResources#68]
Not sure if there's already built in support for these mods but for whatever reason i can't seem to get JER to pick up on Ore Generation Handled by these Mods:

OreTweaker:
http://minecraft.curseforge.com/projects/ore-tweaker?gameCategorySlug=mc-mods&projectID=242436
- [ ] 

Substratum:
http://minecraft.curseforge.com/projects/substratum?gameCategorySlug=mc-mods&projectID=241113
- [ ] 

For now i'm gonna start using the for me "newly discovered" DIY Ore Graph :P
But I wanted to make a post incase this is something you'd like to add as native support.

**Comment by way2muchnoise** [comment]
Native support for mods isn't something I want to do any more as @mezz and my self put a lot of effort in the scanning of the world to create the DIY ore graphs.

**Comment by Lanse505** [comment]
Understandable o/
Thanks anyway ^^

**Comment by Lanse505** [comment]
Acctually @way2muchnoise Quick question, how would this DIY OreChart and Profiling handle in the future having oregen handled differently across different biomes?

Lets say for example that a mod that were to provide us with similar features to CoFH Worldgen.
If people were to set-up oregen on a "Per Biome"-basis, if you run the Profiler for lets say 2500 chunks, and it didn't find the appropriate biome. How would it declare OreGeneration over Biomes?

Does it simply say: 
"so look over these 2500 there is this Avg Number of Ores at these numbers"
or how would it work?

(Sorry for the very poorly worded question but it's starting to get quite late and i'm very tired xD

**Comment by way2muchnoise** [comment]
There is no per biome (there is per dimension tho). It'll give you the same graphs as before only do they look something like this. The scanning is semi random chunks so it isn't that if there is no biome x close that you won't find one during scanning. Also scanning "should" be done in large numbers (2500 seems a decent starting point, but for a decent graph you need like 5000+ at least). That said the graph below is from 200 chunks :D. To finish up there is code support for biomes there is just no support for it in the DIY graphs.
![image](https://cloud.githubusercontent.com/assets/5518998/15870315/239781be-2cf0-11e6-90db-f9e373e0d854.png)

**Comment by Lanse505** [comment]
Neat ^^ 

Thanks for all the info :+1:
