### ISSUE TITLE
JER 1.9.4-0.4.6.39 crashes when looking at some recipes

### ISSUE THREAD

**Issue by Acemcbean** [way2muchnoise/JustEnoughResources#74]
crash report: http://pastebin.com/sCAn5M90

**Comment by way2muchnoise** [comment]
If you can try using the 1.10 version, I know what the problem is and will fix it tomorrow.

**Comment by way2muchnoise** [comment]
@Acemcbean If you want to use the 1.10 version of JEI in 1.9 instance also use the 1.10 version of JER.
