### ISSUE TITLE
[1.10] New profiling not working

### ISSUE THREAD

**Issue by b0bst3r** [way2muchnoise/JustEnoughResources#80]
Perhaps the title is a bit misleading, the actual profiling works but once you reload MC there's nothing on any ores, seeds or anything, vanilla or modded.

This is with     
B:diyData=true

There is a crash in the startup log which may be relevant :- http://pastebin.ubuntu.com/23204744/

jei_1.10.2-3.9.5.257
JustEnoughResources-1.10.2-0.5.1.55
Forge 2088

Link to json - https://www.dropbox.com/s/aq90smmdvgegvnj/world-gen.json?dl=0

**Comment by way2muchnoise** [comment]
New build up on CF soon
