### ISSUE TITLE
RandomThings-Compability

### ISSUE THREAD

**Issue by lumien231** [way2muchnoise/JustEnoughResources#81]
This (lumien231/Random-Things#129) crash was reported on my repo, not sure which mod is causing issues here but the line that's crashing is [this](https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/worldgen/WorldGenCores.java#L184) one. 2 Lines before that i set the block so the te should be there. Do you maybe not "simulate" tes properly or something? (Or am i doing something wrong?)

**Comment by way2muchnoise** [comment]
You might want to add a null check around in there, but I don't think I do anything weird with TEs as chests (in dungeons) get generated just fine.

**Comment by way2muchnoise** [comment]
Does this still happen or can I close it?

**Comment by lumien231** [comment]
Just tested it again and it seems to work fine now so you can probably close it.

**Comment by way2muchnoise** [comment]
Alright if you fix it on your side I'll close it here :D
