### ISSUE TITLE
Pokecube Compatiblty Issue

### ISSUE THREAD

**Issue by Thutmose** [way2muchnoise/JustEnoughResources#82]
It seems the recent change has removed the ability to add in an array of LootDrop for a mob, and requires a resource location instead.  The way Pokecube handles loading in drops from configs, it is much easier to generate and array of LootDrop, than to try to make loot tables to add into the world thing.

Can you re-add a method for the IMobRegistry which takes a collection or array of LootDrop for a case like this?  If not, I can try to make a PR for this in the next few days, if I get the time to do so.

**Comment by way2muchnoise** [comment]
I'll re add the method that add LootDrops. I just thought every thing was loaded from LootTables now days.

**Comment by way2muchnoise** [comment]
Readded in d195386c57a7217292efd8e6f20b5cc9c9f15db8
