### ISSUE TITLE
startup enhancement

### ISSUE THREAD

**Issue by DanHolli123** [way2muchnoise/JustEnoughResources#83]
the startup with this mod installed sometimes fails because my computer closes it because it uses too many resources
I think there should at-least be an option to have it load the drop when playing instead of at startup

**Comment by way2muchnoise** [comment]
Could a log of when it crashes? Maybe I can do something about it.

**Comment by way2muchnoise** [comment]
Is this still an issue in the newer version of JEI/JER?

**Comment by way2muchnoise** [comment]
Closes cause no response.
