### ISSUE TITLE
World Scan Causes Crash

### ISSUE THREAD

**Issue by Plurp13** [way2muchnoise/JustEnoughResources#85]
So i was having issues with the world scan, I tried to scan ten chunks and it just froze up the game so badly I had to force quit it. When I started it up again I scaled way back to 1 chunk and it immediately crashed. I have a crash report but it doesn't actually mention JER as far as I can tell, which is weird, but I figured no harm in reporting it anyway.

http://pastebin.com/mzAt4Snh

I'll try with just JER and JEI too to be sure and if it still crashes I'll add that crash report.

**Comment by Plurp13** [comment]
Boom, still crashes, though it did get a little further it actually told me it was starting to scan the nether before it exploded.

http://pastebin.com/xYBpxFRh

**Comment by way2muchnoise** [comment]
Can you try one of the [newer versions](https://minecraft.curseforge.com/projects/just-enough-resources-jer/files)

**Comment by way2muchnoise** [comment]
@Plurp13 Does this still happen?

**Comment by Plurp13** [comment]
I hadn't checked for a reply past a couple weeks, it seems to work fine with the latest version thanks ^.^
