### ISSUE TITLE
Graph not showing up for mod ores

### ISSUE THREAD

**Issue by kythorn** [way2muchnoise/JustEnoughResources#87]
In recent builds (including the latest alpha and beta releases) I've been unable to get distribution graphs to show up for modded ores such as Tinker's Construct or Substratum. 

I'm in DIY mode, and I've ran a profile of 1000 chunks across all dimensions. I can verify I see data from the mods in question in the json file, but the graphs still don't show up in game for any of the ores introduced by addons in my instance.

I've attached a copy of my world-gen.json in case it helps.

[world-gen.zip](https://github.com/way2muchnoise/JustEnoughResources/files/551386/world-gen.zip)

**Comment by PrinceOfAmber** [comment]
Yep, confirmed happening with cyclic ores in nether and end also.  Link to src in case it helps  https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/java/com/lothrazar/cyclicmagic/world/gen/WorldGenNetherOre.java

**Comment by way2muchnoise** [comment]
Closing due to no response

**Comment by TheTrueForce** [comment]
I'm also finding that this is happening on 1.12.2 with Thermal Foundation and Tinkers' Construct ores. I have not yet run the profiler.

**Comment by way2muchnoise** [comment]
You need to scan the world before any other mod ores will be taken into account. Unless they added their own support for JER, which I don't think they do.

**Comment by TheTrueForce** [comment]
Scan? Do you mean the profiler?

**Comment by way2muchnoise** [comment]
I meant run the `/profile` command, if you tried that and it crashed then you should make a new issue explaining what you did. Include the crash log there, using a paste service like pastebin or gist. Please don't just past the crash log in the issue.

**Comment by TheTrueForce** [comment]
Yeah, copy-pasting the log in the issue is only irritating.
I'll try the command again(in a throwaway world), and if it does crash, I'll slap up an issue.
