### ISSUE TITLE
Custom world gen entries can't be added multiple times for the same block

### ISSUE THREAD

**Issue by The-Fireplace** [way2muchnoise/JustEnoughResources#92]
When I try to add a new entry for Clay, it doesn't show up, just the vanilla one.
https://github.com/The-Fireplace/Fires-Clay-Spawn/blob/master/src/main/java/the_fireplace/clayspawn/compat/JERCompat.java#L28

**Comment by The-Fireplace** [comment]
That commit didn't appear to fix my problem, perhaps I didn't explain clearly enough. I add an additional world generator for Clay, for which, the graph should look something like this:
![2016-11-12_10 40 13](https://cloud.githubusercontent.com/assets/5914284/20239429/5b41b926-a8c5-11e6-9111-d97d08db7003.png)
However, when I add it to JER, using [this code](https://github.com/The-Fireplace/Fires-Clay-Spawn/blob/master/src/main/java/the_fireplace/clayspawn/compat/JERCompat.java#L27), the graph that shows up is still the one for the Vanilla generation:
![2016-11-12_10 40 43](https://cloud.githubusercontent.com/assets/5914284/20239430/5b41bcc8-a8c5-11e6-9c11-2eb6bffa71b5.png)
The expected behavior was it either merging my graph and the vanilla one, or showing two graphs, one for vanilla, and one for my custom generation.

**Comment by way2muchnoise** [comment]
Hmm I thought it would merge correctly now, will look at it some more
