### ISSUE TITLE
"Drops" Section on the ore world gen gui doesn't cycle through on itemstacks using OreDictionary.WILDCARD_VALUE

### ISSUE THREAD

**Issue by The-Fireplace** [way2muchnoise/JustEnoughResources#95]
Here is where I used it, and it doesn't cycle through the options when I look at it in the gui
https://github.com/The-Fireplace/Fires-Clay-Spawn/blob/master/src/main/java/the_fireplace/clayspawn/compat/JERCompat.java#L32

**Comment by way2muchnoise** [comment]
Will have to page @mezz  about this.

**Comment by The-Fireplace** [comment]
You know, after thinking about this more, this really isn't high priority. Now that the data values line up correctly between the generated block and the dropped block, the only way I see this being useful is if we were to allow the block next to the graph to also cycle.

**Comment by way2muchnoise** [comment]
That is what would happen when I fix this :D
