### ISSUE TITLE
Crash when checking mob drop in JEI

### ISSUE THREAD

**Issue by frank89722** [way2muchnoise/JustEnoughResources#99]
A issue when ichun's googlye eye install with JER
When I checking mob drop in jei it would crash like this.

http://pastebin.com/ZHhH6vYE

**Comment by way2muchnoise** [comment]
Can you reproduce this with only JER and Googly eyes? (and there dependencies ofc)

**Comment by frank89722** [comment]
I just tried.
It crash like last time.
